local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {};
}


gt.Const.Strings.CharacterNames <- [
	"Sigurd",
	"Siegfried",
	"Hilmar",
	"Harald",
	"Sigbold",
	"Siegward",
	"Ulfert",
	"Kalle",
	"Espen",
	"Hagen",
	"Ewald",
	"Wenzel",
	"Ejnar",
	"Gunther",
	"Ivar",
	"Jannold",
	"Bertel",
	"Ingolf",
	"Wiedekind",
	"Egon",
	"Casimir",
	"Hilderich",
	"Friedrich",
	"Wendel",
	"Hasso",
	"Wilreich",
	"Hans",
	"Torhelm",
	"Fritz",
	"Mattis",
	"Birk",
	"Arnold",
	"Knut",
	"Adler",
	"Niels",
	"Elmer",
	"Ulfert",
	"Jost",
	"Tostig",
	"Bertram",
	"Albrecht",
	"Kunold",
	"Baldomar",
	"Dietmar",
	"Donbert",
	"Erwin",
	"Caspar",
	"Arne",
	"Edmund",
	"Kunibert",
	"Arnulf",
	"Eduard",
	"Meinolf",
	"Oskar",
	"Giselherr",
	"Reimar",
	"Wernhard",
	"Vander",
	"Werner",
	"Wigald",
	"Willibald",
	"Bjarne",
	"Henrik",
	"Ruthard",
	"Alrik",
	"Hubert",
	"Ernst",
	"Rudolf",
	"Hartbert",
	"Asgeir",
	"Horik",
	"Konrad",
	"Gerhard",
	"Hanke",
	"Guido",
	"Till",
	"Geralt",
	"Hartwig",
	"Thorben",
	"Gisbert",
	"Bruno",
	"Wigmar",
	"Gottfried",
	"Hakon",
	"Goswin",
	"Guntbert",
	"Eckbert",
	"Roger",
	"Gebhard",
	"Ralf",
	"Bernfried",
	"Guntram",
	"Ferdinand",
	"Leonhard",
	"Gerlach",
	"Helmer",
	"Gustav",
	"Gerold",
	"Gero",
	"Gerulf",
	"Emmerich",
	"Karl",
	"Dirk",
	"Falk",
	"Anselm",
	"Diethelm",
	"Alvar",
	"Eberecht",
	"Wilhelm",
	"Hildebert",
	"Erik",
	"Theudobald",
	"Havard",
	"Hakon",
	"Wolfgang",
	"Erling",
	"Kori",
	"Randolf",
	"Rollo",
	"Leif",
	"Lars",
	"Torsten",
	"Ingmar",
	"Asbjorn",
	"Steinar",
	"Reynhart",
	"Baldur",
	"Olaf",
	"Egil",
	"Magnus",
	"Gunnar",
	"Svein",
	"Carsten",
	"Eugen",
	"Anton",
	"Torvald",
	"Bernhard",
	"Einar",
	"Leberecht",
	"Ragnar",
	"Ottmar",
	"Otwin",
	"Balon",
	"Eberold",
	"Bertwin",
	"Oswald",
	"Rabe",
	"Reimund",
	"Wolf",
	"Eberhard",
	"Grimwald",
	"Hugo",
	"Hallstein",
	"Helfrich",
	"Haribert",
	"Balduin",
	"Waldemar",
	"Engelbert",
	"Tobjoern",
	"Erland",
	"Torkel",
	"Horst",
	"Thorismund",
	"Torleif",
	"Erhard",
	"Ulf",
	"Otto",
	"Hermann",
	"Heinrich",
	"Halsten",
	"Kettilmund",
	"Alfgeir",
	"Sorrel",
	"Hartmut",
	"Lothar",
	"Manfred",
	"Reinhold",
	"Alfred",
	"Dietrich",
	"Rupert",
	"Heimrad",
	"Sigmar",
	"Friso",
	"Landrich",
	"Lienhard",
	"Sigmund",
	"Reinhardt",
	"Kurt",
	"Bodo",
	"Volmar",
	"Liebwin",
	"Dieter",
	"Ulrich",
	"Eike",
	"Walram",
	"Malte",
	"Grimald",
	"Berthold",
	"Alberich",
	"Raban",
	"Rumold",
	"Witold",
	"Volker",
	"Volkhart",
	"Bertolf",
	"Walter",
	"Ortwin",
	"Humbert",
	"Adelmar",
	"Konrad",
	"Gernot",
	"Radulf",
	"Ludolf",
	"Giselher",
	"Adelbert",
	"Hjalmar",
	"Reiner",
	"Burkhard",
	"Winrich",
	"Wilderich",
	"Wilfried",
	"Robert",
	"Wolfram",
	"Raimund",
	"Thilmann",
	"Norman",
	"Ludger",
	"Alwin",
	"Markward",
	"Markolf",
	"Hadebrand",
	"Roderick",
	"Rambert"

];

gt.Const.Strings.CharacterNamesFemale <- [
	"Ingrid",
	"Helga",
	"Irma",
	"Adela",
	"Birgit",
	"Beatrix",
	"Bertha",
	"Blanche",
	"Borghild",
	"Brunhild",
	"Frida",
	"Gisela",
	"Gudrun",
	"Hilda",
	"Judith",
	"Sigrid",
	"Sibyle",
	"Sophia",
	"Joanna",
	"Mathilda",
	"Gerhild",
	"Amalie",
	"Agnise",
	"Agathe",
	"Clare",
	"Helena",
	"Ursular",
	"Vronika",
	"Magrit",
	"Eneyde",
	"Elsa",
	"Birgitte",
	"Gissela",
	"Lena",
	"Agness",
	"Adela",
	"Athelyna",
	"Alyna",
	"Milisant",
	"Ade",
	"Evett",
	"Hawyse",
	"Emilina",
	"Elia",
	"Auberee",
	"Jenna"

];
gt.Const.Strings.BarbarianNames <- [
	"Smud",
	"Hirguld",
	"Braum",
	"Grimner",
	"Harif",
	"Skallag",
	"Hylle",
	"Guder",
	"Asberk",
	"Iyrd",
	"Brand",
	"Obrun",
	"Jormal",
	"Joltul",
	"Jotnar",
	"Huggur",
	"Eirik",
	"Hafgufa",
	"Vaettir",
	"Frugar",
	"Vikingur",
	"Brokkr",
	"Hurik",
	"Skarbrand"
];
gt.Const.Strings.BarbarianTitles <- [
	"the Slayer",
	"the Destroyer",
	"the Ravager",
	"the Pillager",
	"the Conquerer",
	"the Slayer",
	"the Defiler",
	"the Despoiler",
	"the Menace",
	"the Headhunter",
	"the Ravager",
	"Skullcrusher",
	"Bonebreaker",
	"Slaughterborne",
	"the Chosen",
	"Battleborn",
	"Ironside",
	"the Bloodied",
	"the Beast",
	"Beastblood"
];
gt.Const.Strings.NobleTitles <- [
	"Count",
	"Count",
	"Baron",
	"Baron",
	"Duke"
];

gt.Const.Strings.NoblewomanTitles <- [
	"Dame",
	"Lady",
	"Baroness",
	"Lady",
	"Dutchess"
];

gt.Const.Strings.SellswordTitles <- [
	"the Butcher",
	"the Berserker",
	"the Dog",
	"the Hound",
	"the Bloody",
	"the Wolf",
	"the Blade",
	"the Impaler",
	"the Younger",
	"the Older",
	"the Merciless",
	"the Red",
	"the Black",
	"Orcbane",
	"the Knightslayer",
	"the Falcon"
];
gt.Const.Strings.SwordmasterTitles <- [
	"the Legend",
	"the Master",
	"the Fencer",
	"the Fast",
	"Quickblade",
	"the Serpent",
	"the Swift",
	"Bladedancer",
	"the Undefeated",
	"the Unbeaten",
	"the Champion",
	"Master of the Realm"
];
gt.Const.Strings.HedgeKnightTitles <- [
	"The Lone Wolf",
	"The Wolf",
	"The Hound",
	"Steelwielder",
	"The Slayer",
	"The Jouster",
	"The Giant",
	"The Mountain",
	"Strongface",
	"The Defiler",
	"The Knightslayer",
	"The Hedge Knight",
	"the Shrubbery",
	"Who Says Ni",
	"The Scourge",
	"The Fallen Knight",
	"Mancrusher",
	"The Exiled",
	"Warshout",
	"The Skulltaker",
	"The Cleaver",
	"The Sentinel",
	"The Courageous",
	"The Chaotic",
	"The Brutal",
	"The Courteous",
	"The Angel",
	"The Heroic",
	"The Protector",
	"The Brave",
	"The Titan",
	"The Loyal",
	"The Merciful",
	"The Butcher",
	"The Horrific",
	"The Invincible",
	"The Slayer",
	"The Bear",
	"The Dragon",
	"The Unicorn",
	"Lionheart",
	"The Humble",
	"The Dreamer",
	"The Trusted",
	"The Mighty",
	"The Strange",
	"Dragonheart",
	"The Prodigy",
	"The Enigma",
	"The Divine",
	"The Black",
	"The Blue",
	"The Red",
	"The White",
	"The Grey",
	"The Cold",
	"The Warm",
	"Of The Ghost",
	"Of The Dawn",
	"Of The Stars",
	"Of The Sky",
	"Of The Night",
	"Of The Twilight",
	"Of The Nightfall",
	"Of The Summer",
	"Of The Winter",
	"Of The Fall",
	"Of The Spring",
	"Of The Water",
	"Of The River",
	"Of The Ice",
	"Of The Road",
	"Of The Snow",
	"Of The River",
	"Of The East",
	"Of The West",
	"Of The South",
	"Of The North"
];

gt.Const.Strings.LadyTitles <- [
	"The Guardian",
	"The Ghost",
	"The Swift",
	"Steelwielder",
	"The Hawk",
	"The Giant",
	"The Mountain",
	"Strongface",
	"The Knightslayer",
	"The Undefeated",
	"The Scourge",
	"The Brute",
	"Mancrusher",
	"The Exiled",
	"The Conqueror",
	"The Skulltaker",
	"The Sentinel",
	"The Courageous",
	"The Chaotic",
	"The Brutal",
	"The Courteous",
	"The Angel",
	"The Heroic",
	"The Protector",
	"The Brave",
	"The Titan",
	"The Loyal",
	"The Merciful",
	"The Butcher",
	"The Horrific",
	"The Invincible",
	"The Slayer",
	"The Bear",
	"The Dragon",
	"The Unicorn",
	"Lionheart",
	"The Humble",
	"The Dreamer",
	"The Trusted",
	"The Mighty",
	"The Strange",
	"Dragonheart",
	"The Prodigy",
	"The Enigma",
	"The Divine",
	"The Black",
	"The Blue",
	"The Red",
	"The White",
	"The Grey",
	"The Cold",
	"The Warm",
	"Of The Ghost",
	"Of The Dawn",
	"Of The Stars",
	"Of The Sky",
	"Of The Night",
	"Of The Twilight",
	"Of The Nightfall",
	"Of The Summer",
	"Of The Winter",
	"Of The Fall",
	"Of The Spring",
	"Of The Water",
	"Of The River",
	"Of The Ice",
	"Of The Road",
	"Of The Snow",
	"Of The River",
	"Of The East",
	"Of The West",
	"Of The South",
	"Of The North"
];

gt.Const.Strings.MasterArcherNames <- [
	"%randomname% the Marksman",
	"Sureshot",
	"%randomname% the Master Archer",
	"%randomname% the Hunter",
	"%randomname% the Sniper",
	"Hundred Paces",
	"%randomname% Quick Shot",
	"The Headhunter"
];
gt.Const.Strings.MasonTitles <- [
	"the Builder",
	"Bricklayer",
	"the Architect",
	"the Artisan"
];
gt.Const.Strings.MilitiaTitles <- [
	"the Conscript",
	"the Militiaman",
	"the Footman"
];
gt.Const.Strings.BrawlerTitles <- [
	"Hamfisted",
	"the Mauler",
	"the Rock",
	"the Stallion",
	"Ironjaw",
	"the Brawler"
];
gt.Const.Strings.PeddlerTitles <- [
	"the Snake",
	"the Weasel",
	"Silver-Tongue",
	"the Sutler",
	"the Peddler",
	"the Merchant"
];
gt.Const.Strings.WitchhunterTitles <- [
	"the Nighthunter",
	"the Witchhunter",
	"the Exorciser",
	"the Saltzpire",
	"the Inquisitor",
	"the Righteous",
	"the Torturer"
];
gt.Const.Strings.GravediggerTitles <- [
	"the Gravedigger",
	"the Shoveler",
	"Gravespotter",
	"the Odd"
];
gt.Const.Strings.RatcatcherTitles <- [
	"Longnose",
	"the Rat",
	"the Ratcatcher",
	"the Tepid"
];
gt.Const.Strings.BastardTitles <- [
	"the Bastard",
	"the Mistake",
	"Cuckchild",
	"the Secret Son",
	"Whoreson",
	"the Tarnish"
];
gt.Const.Strings.PilgrimTitles <- [
	"the Believer",
	"the Seeker",
	"the Thaumaturge",
	"the Pure",
	"the Flagellant",
	"the Pilgrim"
];
gt.Const.Strings.KnightNames <- [
	"Sir Roderick",
	"Sir Egidius",
	"Sir Henrik",
	"Sir Dankwart",
	"Sir Eisenherz",
	"Sir Geofram",
	"Sir Baranor",
	"Sir Wilhelm",
	"Sir Hildebrand",
	"Sir Hilmar",
	"Sir Severin",
	"Sir Starkwart",
	"Sir Elgast",
	"Sir Magnus",
	"Sir Burkhard",
	"Sir Silvan",
	"Sir Lambert",
	"Sir Kuno",
	"Sir Wenzel",
	"Sir Donatus",
	"Sir Albrecht",
	"Sir Hilderich",
	"Sir Sigmund",
	"Sir Steinhart",
	"Sir Hermann",
	"Sir Eckhart",
	"Sir Guidobald",
	"Sir Theo",
	"Sir Eswig",
	"Sir Walram",
	"Sir Casimir",
	"Sir Magnus",
	"Sir Wighart",
	"Sir Otto",
	"Sir Sigismund",
	"Sir Erland",
	"Sir Erkenbrand",
	"Sir Theoderich",
	"Sir Lothar",
	"Sir Wolfhart",
	"Sir Balon",
	"Sir Valdemar",
	"Sir Giselherr",
	"Sir Engelbert",
	"Sir Lancel",
	"Sir Humbert",
	"Sir Emmerich",
	"Sir Grimm",
	"Sir Donbert",
	"Sir Robert",
	"Sir Wolfgang",
	"Sir Kettilmund",
	"Sir Konrad",
	"Sir Rupert",
	"Sir Harald",
	"Sir Roland",
	"Sir Rabe",
	"Sir Siegfried",
	"Sir Kunibert",
	"Sir Dankrad",
	"Sir Leberecht"

];
gt.Const.Strings.LadyNames <- [
	"Lady Jean",
	"Lady Hatchet",
	"Lady Matilda",
	"Lady Isabella",
	"Lady Deborah",
	"Lady Gwendolen",
	"Lady Mavia",
	"Lady Lilliard",
	"Lady Madeira",
	"Lady Hille",
	"Lady Amina",
	"Lady Mary",
	"Lady Beaton",
	"Lady Jean",
	"Lady Avice",
	"Lady Emma",
	"Lady Joan",
	"Lady Margery",
	"Lady Albree",
	"Lady Alia",
	"Lady Ela",
	"Lady Gisella",
	"Lady Elisa",
	"Lady Tamsin",
	"Lady Anabella",
	"Lady Beatrice",
	"Lady Clarae",
	"Lady Emilia",
	"Lady Constance",
	"Lady Florencia",
	"Lady Joye",
	"Lady Lucia",
	"Lady Arrianna",
	"Lady Pavia",
	"Lady Prudence",
	"Lady Sabina",
	"Lady Ursula",
	"Lady Grace",
	"Lady Yvone"
];


gt.Const.Strings.OrcWarlordNames <- [
	"Illska Ghul",
	"Skabskra",
	"Urosh",
	"Kushtrum",
	"Goth Na Ari",
	"Obrokk",
	"Blok Sapat",
	"Gorash",
	"Mogtul",
	"Thraktar",
	"Gorgash-Ghul",
	"Maruk",
	"Warak Na Borash",
	"Urgat",
	"Durgash",
	"Skalleklyfta",
	"Margash Borash",
	"Borgash",
	"Goruk Sapat",
	"Karosh Urgat",
	"Horgash Ghul",
	"Naguk",
	"Shadok",
	"Bakh Lob",
	"Corgat",
	"Urmuk Ghul",
	"Mug Nadar",
	"Vras Ushtar",
	"Brulk Zogtar",
	"Sapat Blok",
	"Mosh Shagit",
	"Gajit Bukol",
	"Blot Kakok",
	"Thrak Talun",
	"Drod Kazan",
	"Oxshak",
	"Urdanog",
	"Trok Oborr",
	"Bolvag Shrub",
	"Ug Shatup",
	"Shatratog",
	"Buruk Skag",
	"Ilska Sapat",
	"Grug Zartum",
	"Grommok",
	"Arvius",
	"Ogrul",
	"Shura Nak"
];
gt.Const.Strings.BanditLeaderNames <- [
	"The Butcher",
	"%randomname% the Knife",
	"%randomname% the Slaughterer",
	"King %randomname%",
	"%randomname% the Ox",
	"The Wolf",
	"%randomname% the Marauder",
	"%randomname% the Snake",
	"%randomname% Four Fingers",
	"Barabas Brimstone",
	"Rotor Ravensblack",
	"Black Crow Balthasar",
	"The Bull of %randomtown%",
	"%randomname% Bloodbeard",
	"Mead Jar %randomname%",
	"Bloody %randomname%",
	"Dreaded %randomname%",
	"The Swine",
	"%randomname% the Cruel",
	"%randomname% the Outcast",
	"The Robber Baron",
	"Red Viper",
	"%randomname% the Brigand",
	"%randomname% the Scourge",
	"The Raiding Lord",
	"The Manhunter",
	"Big %randomname%",
	"%randomname% the Savage",
	"Infamous %randomname%",
	"The Menace of %randomtown%",
	"%randomname% the Red",
	"Gunther the Grinning",
	"%randomname% the Hyena",
	"%randomname% the Hawk",
	"%randomname% the Mad",
	"%randomname% the Brute",
	"%randomname% the Pillager",
	"Lars the Lunatic",
	"%randomname% the Free",
	"Black Eyes Einhart",
	"Oswall the Odd",
	"Brokk Mad Eyes",
	"%randomname% the Ashen Prince",
	"The Scourge of %randomtown%",
	"%randomname% the Bleak",
	"Bleak Blade Ingram",
	"%randomname% the Pickpocket",
	"Mickel Copperheart",
	"Casper the Cutpurse",
	"Ottel Bleakheart",
	"Joost Crowntaker",
	"Baltasar the Toothless",
	"Walter the Spider",
	"August the Gravedigger",
	"Urban Goodman",
	"%randomname% the Blade",
	"Mad %randomname%",
	"Slithering %randomname%",
	"%randomname% the Smug",
	"%randomname% the Rat",
	"Toothless %randomname%",
	"Cheating %randomname%",
	"%randomname% the Nightmare",
	"%randomname% Three Fingers",
	"Scarface %randomname%",
	"Lucky %randomname%",
	"Poison %randomname%",
	"Cackling %randomname%",
	"%randomname% the Swindler",
	"%randomname% the Menace",
	"%randomname% the Viper"
];
gt.Const.Strings.KrakenNames <- [
	"Ogg-Sattoth the Grand Devourer",
	"Kha-Athlu the All-Ender",
	"Shaggaruth the Unending",
	"Gla-Oth the Endless Maw",
	"Gu-Shogg the Thousand-Armed Thresher",
	"Chtan-Nahitil the Gorger of All",
	"Xa-Shutar the Eater of Worlds",
	"Thohochoth the All-Ender",
	"Naccorath the Eternal",
	"Xapocathlu the All-Reaching"
];
gt.Const.Strings.CharacterNamesFemaleNorse <- [
	"Agata",
	"Alfhilda",
	"Arnlaug",
	"Birna",
	"Brunhild",
	"Bylgja",
	"Dagrun",
	"Drifa",
	"Edda",
	"Eir",
	"Elli",
	"Embla",
	"Fenja",
	"Frigg",
	"Gigja",
	"Groa",
	"Gudrun",
	"Gullveig",
	"Halla",
	"Heidrun",
	"Helga",
	"Hrefna",
	"Hulda",
	"Ida",
	"Inga",
	"Ingrid",
	"Ingunn",
	"Johanna",
	"Jorunn",
	"Katla",
	"Kolbrun",
	"Kristin",
	"Laufey",
	"Magdalena",
	"Magna",
	"Marta",
	"Mette",
	"Nanna",
	"Oda",
	"Ragna",
	"Runa",
	"Sif",
	"Signy",
	"Sigrid",
	"Sigrun",
	"Solveig",
	"Svana",
	"Tekla",
	"Tora",
	"Torunn",
	"Una",
	"Valborg",
	"Valdis",
	"Yrsa"
];
gt.Const.Strings.InventorTitles <- [
	"the Inventor",
	"the Curious",
	"the Peculiar",
	"the Inquisitive",
	"the Utilitarian",
	"the Serendipitous",
	"the Eclectic",
	"the Tinkerer"
];
gt.Const.Strings.AncientDeadNames <- [
	"Brasus",
	"Gudila",
	"Ostracon",
	"Dardanos",
	"Duras",
	"Mucatra",
	"Cothelas",
	"Arzaru",
	"Decalus",
	"Akamas",
	"Kavaros",
	"Comoscius",
	"Moskon",
	"Rholes",
	"Tarbus",
	"Apulon",
	"Napucon",
	"Barsobis"
];
gt.Const.Strings.AncientDeadTitles <- [
	"the Returned",
	"the Restorator",
	"the Ancient",
	"the Destroyer",
	"the Guardian",
	"the Hunter",
	"the Second",
	"the Herald",
	"the Unearthed",
	"the Forgotten",
	"the Protector",
	"the Honored",
	"the Defender",
	"of the North"
];
gt.Const.Strings.GoblinNames <- [
	"Nox",
	"Grubb",
	"Sharax",
	"Zuggut",
	"Grisnik",
	"Zatak",
	"Finex",
	"Zugtakr",
	"Velok",
	"Zatox",
	"Naxanix",
	"Vlixix",
	"Snarf",
	"Ratox"
];
gt.Const.Strings.GoblinTitles <- [
	"the Stabber",
	"the Insidious",
	"Throatcutter",
	"Knifelicker",
	"the Skinner",
	"the Headhunter",
	"Eyegouger",
	"Rotgut",
	"Longnose",
	"the Cutter",
	"Nosebiter",
	"the Sticker"
];
gt.Const.Strings.FallenHeroTitles <- [
	"the Decayed",
	"the Unburied",
	"the Rotten",
	"the Defiled",
	"the Returned",
	"the Undying",
	"the Cursed",
	"the Corrupted",
	"the Unbreakable",
	"the Oathbreaker",
	"the Forgotten",
	"the Lost",
	"the Fallen Hero",
	"the Cruel",
	"the Returned",
	"the Prince of Rot",
	"the Hollow"
];