local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "an " : "a ";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "An " : "A ";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1st",
	"2nd",
	"3rd",
	"4th",
	"5th",
	"6th",
	"7th",
	"8th",
	"9th",
	"10th",
	"11th",
	"12th",
	"13th",
	"14th",
	"15th",
	"16th",
	"17th",
	"18th",
	"19th",
	"20th"
];
gt.Const.Strings.Difficulty <- [
	"Beginner",
	"Veteran",
	"Expert"
];
gt.Const.Strings.EntityName <- [
	"Necromancer",
	"Wiederganger",
	"Armored Wiederganger",
	"Fallen Hero",
	"Rachegeist",
	"Ancient Auxiliary",
	"Ancient Legionary",
	"Ancient Honor Guard",
	"Ancient Priest",
	"The Conqueror",
	"Necrosavant",
	"Geist",
	"Nachzehrer",
	"Orc Young",
	"Orc Berserker",
	"Orc Warrior",
	"Orc Warlord",
	"Militia",
	"Militia Marksman",
	"Militia Veteran",
	"Militia Captain",
	"Bounty Hunter",
	"Peasant",
	"Caravan Hand",
	"Caravan Guard",
	"Caravan Cart",
	"Footman",
	"Zweihander",
	"Billman",
	"Arbalester",
	"Standard Bearer",
	"Sergeant",
	"Knight",
	"Donkey",
	"Brigand Thug",
	"Brigand Poacher",
	"Brigand Marksman",
	"Brigand Raider",
	"Brigand Leader",
	"Goblin Ambusher",
	"Goblin Skirmisher",
	"Goblin Overseer",
	"Goblin Shaman",
	"Goblin Wolfrider",
	"Wolf",
	"Wardog",
	"Armored Wardog",
	"Mercenary",
	"Mercenary",
	"Swordmaster",
	"Hedge Knight",
	"Master Archer",
	"Greenskin Catapult",
	"Cultist",
	"Direwolf",
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",
	"Webknecht",
	"Webknecht Eggs",
	"Alp",
	"Hexe",
	"Schrat",
	"Sapling",
	"Wildman",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayer",
	"Nightmare"
];
gt.Const.Strings.EntityNamePlural <- [
	"Necromancers",
	"Wiedergangers",
	"Armored Wiedergangers",
	"Fallen Heroes",
	"Rachegeists",
	"Ancient Auxiliaries",
	"Ancient Legionaries",
	"Ancient Honor Guards",
	"Ancient Priests",
	"The Conqueror",
	"Necrosavants",
	"Geists",
	"Nachzehrers",
	"Orc Young",
	"Orc Berserkers",
	"Orc Warriors",
	"Orc Warlords",
	"Militia",
	"Militia Marksmen",
	"Militia Veterans",
	"Militia Captains",
	"Bounty Hunters",
	"Peasants",
	"Caravan Hands",
	"Caravan Guards",
	"Caravan Carts",
	"Footmen",
	"Zweihanders",
	"Billmen",
	"Arbalesters",
	"Standard Bearers",
	"Sergeants",
	"Knights",
	"Donkeys",
	"Brigand Thugs",
	"Brigand Poachers",
	"Brigand Marksmen",
	"Brigand Raiders",
	"Brigand Leaders",
	"Goblin Ambushers",
	"Goblin Skirmishers",
	"Goblin Overseers",
	"Goblin Shamans",
	"Goblin Wolfriders",
	"Wolves",
	"Wardogs",
	"Armored Wardogs",
	"Mercenaries",
	"Mercenaries",
	"Swordmasters",
	"Hedge Knights",
	"Master Archers",
	"Greenskin Catapults",
	"Cultists",
	"Direwolves",
	"Lindwurms",
	"Unholds",
	"Unholds",
	"Unholds",
	"Webknechts",
	"Webknecht Eggs",
	"Alps",
	"Hexen",
	"Schrats",
	"Saplings",
	"Wildmen",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayers",
	"Nightmares"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "Boulder",
	Shrubbery = "Shrubbery",
	Tree = "Tree",
	Brush = "Brush",
	Cartwheel = "Old Cartwheel",
	RuinedPillar = "Ruined Pillar",
	Cart = "Caravan Cart",
	Donkey = "Donkey"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "A large stone boulder. Blocks movement and line of sight.",
	Shrubbery = "Very dense shrubbery that blocks movement and line of sight.",
	Tree = "A large tree with a massive trunk.",
	TreeSwamp = "This tree is rotten and long dead.",
	TreeTrunk = "A treetrunk half covered in foul water.",
	Brush = "Very dense shrubbery that blocks movement and line of sight.",
	Cartwheel = "The old and broken wheel of an oxcart.",
	RuinedPillar = "TODO",
	Cart = "A cart full of trading goods.",
	Donkey = "A donkey used for pulling heavy carts."
};
gt.Const.Strings.ShipNames <- [
	"Summer Daze",
	"Merry Mist",
	"Howl of the Sea",
	"Coral Secret",
	"Sandy Bay",
	"Lady of the Sea",
	"Solitaire",
	"Brunhild",
	"Mathilda",
	"Comet",
	"Tetrarch",
	"Lofjord",
	"Autumn Wind",
	"Poundmaker",
	"Brakel",
	"Seven Stars",
	"Dark Omen",
	"Concord",
	"Albatros",
	"Golden Horse",
	"Sea Nymph",
	"Twisted Fate",
	"King\'s Bounty",
	"Bald Monk",
	"Golden Sun",
	"Vanity",
	"Brazen",
	"Tiger\'s Claw",
	"Sycamore",
	"Noble Runner",
	"Bleak Moon",
	"Clansman",
	"Whale\'s Voyage",
	"Quickmatch",
	"Blackfly",
	"Ejnar Erikson",
	"Lindwurm",
	"Supreme",
	"Griffon",
	"Axford",
	"Bertha",
	"Seagull",
	"Belzebub"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"Iron Ravens",
	"Golden Order",
	"Swords of the South",
	"Wolves of Bleak Forest",
	"Black Shields",
	"Iron Crown Company",
	"Radobrecht\'s Swords",
	"Whistling Arrows",
	"Azure Boars",
	"Fang and Coin",
	"Red Legion",
	"Hungry Hounds",
	"Crimson Daggers",
	"King\'s End Company",
	"Black Company",
	"Second Sons",
	"Walther\'s Fellowship",
	"Grudgebringers",
	"Bernhard\'s Bears",
	"Silver Claw",
	"Iron Brotherhood",
	"Orcbane Company",
	"Iron Covenant",
	"Unbroken Third",
	"Dogs of War",
	"Falkenberg\'s Legion",
	"Free Men",
	"Lords of War",
	"Northern Company",
	"Forsaken Returned",
	"White Company",
	"Widowmakers",
	"Cold Hearts Company",
	"Burning Sun Company",
	"Chosen Few",
	"Dead Men",
	"Bronzeheads",
	"Markland Pikes",
	"Hammerguard",
	"Crowntakers",
	"Silverreach Spears",
	"The Iron Pact",
	"The Blood Bound",
	"The Bulwark",
	"Dawn\'s March",
	"Sons of Winter",
	"Company of the River House",
	"Flaming Comet Company",
	"The Grand Company",
	"Rightful Ravagers",
	"The Host",
	"Forsaken Brigade",
	"Battle\'s Chosen",
	"Bringers of Peace",
	"Shields of the Night",
	"The Mongrels",
	"The Bone Wardens",
	"Lost Legion"
];
gt.Const.Strings.NobleHouseNames <- [
	"Grimmund",
	"Weilburg",
	"Armsberg",
	"Gota",
	"Eisenstein",
	"Grauwall",
	"Rabenholt",
	"Sommerwein",
	"Winterhall",
	"Ruhmolt",
	"Adelreich",
	"Perowinger",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Horn",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Kaltenborn",
	"Krieger",
	"Steinwall",
	"Harkon",
	"Osten"
];
gt.Const.Strings.BusinessReputation <- [
	"Treacherous",
	"Incompetent",
	"Unreliable",
	"Unknown",
	"Recognized",
	"Reliable",
	"Competent",
	"Professional",
	"Reputable",
	"Famed",
	"Great",
	"Glorious",
	"Fabled",
	"Legendary",
	"Invincible",
	"Immortal"
];
gt.Const.Strings.MoralReputation <- [
	"Dreaded",
	"Cruel",
	"Merciless",
	"Notorious",
	"Neutral",
	"Neutral",
	"Kind",
	"Good",
	"Chivalrous",
	"Saintly"
];
gt.Const.Strings.Relations <- [
	"Hostile",
	"Threatening",
	"Unfriendly",
	"Cold",
	"Neutral",
	"Neutral",
	"Open",
	"Friendly",
	"Very Friendly",
	"Allied"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"None",
	"Dirt Road",
	"Clay Road",
	"Cobblestone Road",
	"Grassland",
	"Dirt",
	"Forest",
	"Muddy Earth",
	"Plashy Grass",
	"Murky Water",
	"Steppe",
	"Dry Steppe",
	"Tundra",
	"Snow",
	"Light Snow",
	"Stone",
	"Stone"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"None",
	"A dirt road originating from constant use by humans and animals.",
	"A primitve road consisting of tamped clay.",
	"A cobblestone road used for carriages and larger vehicles.",
	"Short grass on flat and solid ground.",
	"Bare and flat earth with barely any vegetation.",
	"Forest ground covered in a thick and soft mossy layer.",
	"Dark and muddy earth.",
	"Mostly firm ground covered in tall and soft grass.",
	"Shallow, murky water covering a soft and muddy ground.",
	"Flat and firm ground covered with dry and shriveled grass.",
	"Hard patches of earth completely dried out by sun and heat.",
	"Flat and arid ground covered in rough grasses and weeds.",
	"Frozen ground covered in a thick layer of snow.",
	"Frozen ground covered in a light layer of snow.",
	"Smooth stone ground granting a good footing.",
	"TODO"
];
gt.Const.Strings.UI <- {
	Introduction = "You soak in the cool morning air. As the sun slowly rises, so does a new chapter in your life begin. After years of bloodying your sword for meager pay you\'ve saved up enough crowns to start your very own mercenary company. With you are %allbrothers% with whom you\'ve fought before side by side in the shieldwall. You are their commander now, the leader of the %companyname%.\n\nAs you travel the lands you should hire new men in the villages and cities to fill your ranks. Many who offer their services will have never picked up a real weapon before. Maybe they are desperate, maybe they are greedy for quick spoils of war. Most of them will die on the battlefield. But do not be discouraged. Such is the mercenary life, and the next village will always have new men eagerly looking for a new start in life.\n\nThe lands are dangerous these times. Robbers and pillagers lay in ambush by the roads, wild beasts roam the dark forests and orc tribes are restless in the swamps to the east. There are rumors even of dark magic being at work, the dead rising from their graves and walking again. There is plenty of opportunity to earn good money, whether by taking on contracts you can find in the villages, cities and strongholds all over the land, or by venturing out on your own to explore and raid.\n\nYour men look to you to give a command. They live and die for the %companyname% now.\n\n[color=#bd9d71]EARLY ACCESS DISCLAIMER: This version is still heavily work in progress and does not represent the final quality of the product. Features may be incomplete or missing, the UI is unskinned as of yet, there will be bugs, and the balancing and progression of the economy, resources and enemies may need tweaking and can be too challenging or easy occasionally. A lot of additional content will be added over the course of the Early Access, including more enemies, items, contracts, terrain types, unique locations, story events and other features.[/color]",
	FleeDialogueConsequences = "Sometimes it\'s better to do a tactical retreat in order to live and fight another day. The men will attempt to reach the edges of the map by themselves and then safely retreat. However, the enemy may catch up, and anyone currently engaged may not be able to get away unscathed or even alive.",
	RetreatDialogueConsequences = "The enemy is battered and beaten. Those few still alive scatter away in all directions. Will you hunt them down to claim their heads and possessions, or declare the battle won?"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"Existing partly in dreams",
	"Existing partly in dreams",
	"Existing mostly in dreams",
	"Existing mostly in dreams"
];
gt.Const.Strings.BodyPartName <- [
	"body",
	"head"
];
gt.Const.Strings.ItemSlotName <- [
	"Body",
	"Head",
	"Mainhand",
	"Offhand",
	"Accessory",
	"Bag"
];
gt.Const.Strings.World.TimeOfDay <- [
	"Dawn",
	"Morning",
	"Midday",
	"Afternoon",
	"Evening",
	"Dusk",
	"Night",
	"Dawn"
];
gt.Const.Strings.Direction <- [
	"north",
	"north-east",
	"south-east",
	"south",
	"south-west",
	"north-west",
	"<undefined>"
];
gt.Const.Strings.Direction8 <- [
	"north",
	"north-east",
	"east",
	"south-east",
	"south",
	"south-west",
	"west",
	"north-west"
];
gt.Const.Strings.Terrain <- [
	"",
	"in the ocean",
	"on the plains",
	"in the swamps",
	"on the hills",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the mountains",
	"",
	"",
	"in the snow",
	"in the wastelands",
	"in the tundra",
	"in the steppe",
	"on the shore"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"bay",
	"plains",
	"swamp",
	"hills",
	"forest",
	"forest",
	"forest",
	"forest",
	"mountain",
	"",
	"",
	"snow",
	"wastelands",
	"tundra",
	"steppe",
	"shore"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Stormy Sea",
		"Kraken\'s Refuge",
		"White Horses Sea",
		"Thousand Gulls Sea",
		"Deep Depths",
		"Rainy Ocean",
		"Unbound Ocean",
		"Tempest Ocean",
		"Thunder Sea",
		"Great Sea",
		"Surging Sea",
		"Pearl Sea",
		"Howling Sea",
		"Cruel Sea",
		"Arching Tides Ocean",
		"Whispering Waves Sea",
		"Soft Ripple Sea",
		"Green Sea",
		"Sea of Turning Tides",
		"Wailing Ocean",
		"Foamy Shallows",
		"Murky Tide Ocean",
		"Shimmering Expanse",
		"Azure Expanse",
		"The Raging Gulf",
		"The Shimmering Depths"
	],
	[
		"Vendland",
		"Speedwell Fields",
		"Plainshire",
		"Vinland",
		"Lowlands",
		"Windlands",
		"Wide Watch",
		"Glaucious Domain",
		"Rich Meadows",
		"Markland",
		"Fast Clouds County",
		"Fairdale",
		"Fleetfeet\'s Range",
		"Wanderer\'s Boon",
		"Valeshire",
		"Ridland",
		"Greenfold",
		"Hogfolk",
		"Durum",
		"Shallowford",
		"Two Fields",
		"Kingmill",
		"Minceacre",
		"Glendale",
		"Brillfold",
		"Kindon",
		"Greenmere",
		"Mooseridge",
		"Altmark",
		"Neumark",
		"Fair Range",
		"Middlemark",
		"Grasslands",
		"Moss Valley",
		"Wideacre",
		"Southbloom",
		"Dawnland",
		"Oak Wood Meadows",
		"Southwind Acres",
		"Meadowcove",
		"Willow\'s Fields",
		"Grand View Pastures",
		"Nightingale Valley",
		"Silversage Fields",
		"Heartsong\'s Range"
	],
	[
		"Black Marshes",
		"Dead Ponds",
		"Tar Fields",
		"Peatfold",
		"Suffocating Bog",
		"Eerie Marshes",
		"Black Morass",
		"Sticky Wallow",
		"Dreaded Mire",
		"Murky Swamplands",
		"Mortun",
		"Blackfan",
		"Gallowsbog",
		"Dungslump",
		"Houndsmarsh",
		"Shipreath Marsh",
		"Cursed Lands",
		"Grimdowns",
		"The Reeds",
		"Froghold",
		"Spidergrove",
		"Duke\'s Demise",
		"Bottomless Pits",
		"Poisonbreath Marshes",
		"Froglickers Grove",
		"Deadbottom",
		"The Wetlands",
		"The Marshlands",
		"Black Mud",
		"Desolate Moor",
		"Black Fumes Polder",
		"Endless Polder",
		"Peat Basin",
		"Riverland Glades",
		"Southland Bowels",
		"Azure Marsh",
		"Thousand Mirrors Bog",
		"The Narrow Quag",
		"Glades of Decay",
		"Ashen Wetlands",
		"Savage Bog",
		"Mire of the Whisp",
		"Forbidden Waters",
		"Dreadmoor"
	],
	[
		"Bonefold Barrow",
		"Knight\'s Axe Hills",
		"Skullsbreath Mound",
		"Ancient Knolls",
		"Oldlock Hills",
		"The Hummocks",
		"Knowesfold",
		"Ancient Cairns",
		"Humming Hills",
		"Sharp Rocks",
		"Misty Barrows",
		"Boulderhills",
		"Scree Barrows",
		"Bed Load Knolls",
		"Ghost Hills",
		"Banshee Mounds",
		"Shinglehumps",
		"Earthwatch Hills",
		"Giant\'s Pebbles",
		"Buried Snake Hills",
		"Skullslide Hills",
		"Rustcave Hills",
		"Witchmount Hills",
		"Juniper Hills",
		"White Goat Mounds",
		"Barum",
		"The Reach",
		"Whispering Hills",
		"The Bronze Hills",
		"Willowshire Hillside",
		"The Scarlet Hills",
		"Giant\'s Slopes",
		"The Gloomy Hills",
		"The Collapsing Hills"
	],
	[
		"Bleak Forest",
		"Dire Woods",
		"Dismal Woods",
		"Dusky Forest",
		"Scoundrels\' Forest",
		"Boar Woods",
		"Bandit\'s Rest",
		"Splinterdale",
		"Spiderwood",
		"Tickbrake",
		"Druid\'s Grove",
		"Brittle Branch Woods",
		"White Wolf\'s Home",
		"Ravenhold",
		"Needlegrove",
		"Rustling Thicket",
		"Mossy Pine Woods",
		"Crows Nest",
		"Black Forest",
		"Prowlers Woods",
		"Gloomy Woods",
		"Wolfwood",
		"Black Woods",
		"Murmuring Woods",
		"Dark Thorn Wilds",
		"Hedgehog Thicket",
		"Misty Covert",
		"Borderdale",
		"Temple Grove",
		"Wretched Woods",
		"Elder Woods",
		"Deep Covert",
		"Macaw Woods",
		"Hexenwald"
	],
	[],
	[
		"Ancient Forest",
		"Ranger\'s Rest",
		"Valley of the Deer",
		"Oldgrowth",
		"Rampants",
		"Ironoak Grove",
		"Hunter\'s Bosk",
		"Royal Grounds",
		"Sylvan Woods",
		"Fox and Hare Woods",
		"Snapping Twig Forest",
		"Antlerfold",
		"Old Forest",
		"Greenwood Forest",
		"Mossy Woods",
		"Misty Woods",
		"The Sea of Trees",
		"Timberland",
		"Whispering Groves",
		"Grand Hare Woods",
		"Chestnut Grove",
		"Snake\'s Covert",
		"Blackwood Forest",
		"Stormy Woods",
		"Rustling Thicket",
		"Wicked Woods",
		"Gray Toad Woodlands",
		"Treewalker Woodlands",
		"Jagged Woods",
		"Stag\'s Grounds",
		"Crowned Oak Forest",
		"Elderberry Woods",
		"Elm Grove",
		"Black Mole Woods",
		"Brookwood",
		"Springwood",
		"Everwoods"
	],
	[
		"Red Worm Woods",
		"Fiery Woods",
		"Smoldering Woods",
		"Ember Forest",
		"Vibrant Grove",
		"Foxfold Forest",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Blood Woods",
		"Blazing Forest",
		"Vermillion Woods",
		"Crimson Forest",
		"Auburn Woods",
		"Redwood",
		"Badger\'s Covert",
		"Birch Timberland",
		"Waterwood Forest",
		"Pyrewood",
		"Beatroot Wilds",
		"Bogwood Grove",
		"Yellowleaf\'s Range",
		"Bloodbloom Woods",
		"Redbark Forest",
		"Firerock Grove"
	],
	[
		"Spine of the World",
		"Sleeping Giants Back",
		"Jagged Spires",
		"Wall of the Gods",
		"Dreaded Rocks",
		"Rocky Ridge",
		"Jagged Summit",
		"Silver Ridge",
		"Misty Summit",
		"Iron Mountains",
		"Goathorns",
		"Dragonteeth",
		"Highrise",
		"Eagleflight",
		"Grimroof",
		"Dunspike",
		"Dreadhorn",
		"Ravensbeak",
		"Mount Bulkhead",
		"Bulwark",
		"Cloddheads",
		"Browslopes",
		"Hero\'s Fall",
		"Yawning Gaps",
		"Mammothshoulders",
		"Swellpike Heights",
		"Bald Crown",
		"Cloudcrest",
		"Evermist Mountains",
		"Slaughtermount",
		"The Rift",
		"The Thundering Peaks",
		"Decayed Heights",
		"The Glistening Heights",
		"Deserted Rise",
		"The Vast Rise",
		"Moonlit Peaks",
		"The Ashen Pinnacle",
		"The Bare Peaks",
		"The Shadow Mountains",
		"Grimestone Peaks",
		"Brimstone Shoulders",
		"Iron Peaks"
	],
	[],
	[],
	[
		"White Waste",
		"Frozen Plains",
		"Sea of Snow",
		"White Wilderness",
		"Silver Plains",
		"Howling Wastes",
		"Silver Flats",
		"Everwinter",
		"Frozen North",
		"World\'s Rim",
		"Coldend",
		"Wintermore",
		"Icemark",
		"Spikewind",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Ragwilds",
		"Barrens",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands"
	],
	[]
];
gt.Const.Strings.Distance <- [
	"close by",
	"not far",
	"some way",
	"a long way",
	"far",
	"far away"
];
gt.Const.Strings.PartyStrength <- [
	"Puny",
	"Weak",
	"Average",
	"Strong",
	"Dangerous",
	"Deadly",
	"Invincible"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"A few",
	"Some",
	"Many",
	"Lots of",
	"A plethora of"
];
gt.Const.Strings.PerkName <- {
	TrophyHunter = "Trophy Hunter",
	Bruiser = "Bruiser",
	Crusher = "Crusher",
	CloseCombatArcher = "Close Combat Archer",
	Bullseye = "Bullseye",
	Ballistics = "Ballistics",
	Berserk = "Berserk",
	Slaughterer = "Slaughterer",
	BetweenTheEyes = "Between the Eyes",
	DevastatingStrikes = "Devastating Strikes",
	KillingFrenzy = "Killing Frenzy",
	ShieldBash = "Shield Bash",
	Brawny = "Brawny",
	Stalwart = "Stalwart",
	Taunt = "Taunt",
	Steadfast = "Steadfast",
	Colossus = "Colossus",
	Deflect = "Deflect",
	Evade = "Evade",
	ShieldExpert = "Shield Expert",
	NineLives = "Nine Lives",
	BatteringRam = "Battering Ram",
	LastStand = "Last Stand",
	Ironside = "Ironside",
	BattleForged = "Battle Forged",
	BagsAndBelts = "Bags and Belts",
	Rebound = "Rebound",
	Feint = "Feint",
	Student = "Student",
	Lookout = "Lookout",
	Zweihander = "Zweihander",
	Pathfinder = "Pathfinder",
	FortifiedMind = "Fortified Mind",
	Captain = "Sergeant",
	BoondockBlade = "Boondock Blade",
	ArtfulDodger = "Artful Dodger",
	InspiringPresence = "Inspiring Presence",
	QuickHands = "Quick Hands",
	CripplingStrikes = "Crippling Strikes",
	Duelist = "Duelist",
	Vengeance = "Vengeance",
	DoubleStrike = "Double Strike",
	Nimble = "Nimble",
	Dodge = "Dodge",
	HoldOut = "Resilient",
	Anticipation = "Anticipation",
	SteelBrow = "Steel Brow",
	CoupDeGrace = "Executioner",
	Weaponmaster = "Weaponmaster",
	FullForce = "Full Force",
	FastAdaption = "Fast Adaptation",
	BloodyHarvest = "Bloody Harvest",
	SunderingStrikes = "Sundering Strikes",
	BattleFlow = "Battle Flow",
	HeadHunter = "Head Hunter",
	RallyTheTroops = "Rally the Troops",
	Fearsome = "Fearsome",
	Indomitable = "Indomitable",
	Furor = "Furor",
	Debilitate = "Debilitate",
	Footwork = "Footwork",
	Rotation = "Rotation",
	PerfectFocus = "Perfect Focus",
	ReturnFavor = "Return Favor",
	Underdog = "Underdog",
	Sprint = "Sprint",
	Recover = "Recover",
	Inspire = "Inspire",
	Gifted = "Gifted",
	FirstMove = "First Move",
	FirstAid = "First Aid",
	Adrenalin = "Adrenaline",
	Backstabber = "Backstabber",
	LoneWolf = "Lone Wolf",
	ReachAdvantage = "Reach Advantage",
	Overwhelm = "Overwhelm",
	SpecBow = "Bow Mastery",
	SpecCrossbow = "Crossbow Mastery",
	SpecThrowing = "Throwing Mastery",
	SpecAxe = "Axe Mastery",
	SpecCleaver = "Cleaver Mastery",
	SpecDagger = "Dagger Mastery",
	SpecSword = "Sword Mastery",
	SpecSpear = "Spear Mastery",
	SpecPolearm = "Polearm Mastery",
	SpecHammer = "Hammer Mastery",
	SpecMace = "Mace Mastery",
	SpecFlail = "Flail Mastery",

	vazl_ValaInscriptionMastery = "Inscription Mastery",
	vazl_ValaInscribeWeapon = "Inscribe Weapon",
	vazl_ValaInscribeHelmet = "Inscribe Helmet",
	vazl_ValaInscribeArmor = "Inscribe Armor",
	vazl_ValaInscribeShield = "Inscribe Shield"
};
gt.Const.Strings.PerkDescription <- {
	ReturnFavor = "Unlocks the \'Return Favor\' skill which when active has a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] chance to stun any opponent missing a melee attack against this character in retaliation. Immunities and resistances against being stunned still apply.",
	PerfectFocus = "Unlocks the \'Perfect Focus\' skill which allows the use of all other skills for one round at half the normal Action Point cost (rounded down), but double the fatigue cost.",
	Rotation = "Unlocks the \'Rotation\' skill which allows two characters to switch places while ignoring Zone of Control as long as neither character is stunned, rooted or otherwise disabled.",
	Footwork = "Unlocks the \'Footwork\' skill which allows you to leave a Zone of Control without triggering free attacks by using skillful footwork.",
	Debilitate = "Unlocks the \'Debilitate\' skill which can prime your next attack to cripple a target for one turn, reducing their ability to inflict damage by [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Furor = "Unlocks the \'Furor\' skill which allows for an unlimited number of other skill uses for a single turn until the character is completely fatigued.",
	Indomitable = "Unlocks the \'Indomitable\' skill which grants a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] damage reduction and immunity to being stunned, knocked back or grabbed for one turn.",
	RallyTheTroops = "Unlocks the \'Rally\' skill which can rally fleeing allies, and raise morale of all nearby allies to a steady level. The higher the Resolve of the character using the skill, the higher the chance to succeed.",
	Adrenalin = "Unlocks the \'Adrenaline\' skill which puts you first in the turn order for the next round, to have another turn before your enemies do. Feel the adrenaline rushing through your veins!",
	FirstAid = "Unlocks the \'First Aid\' skill which can stop bleeding effects, including those from serious injuries, during combat. Does not heal hitpoints.",
	Fearsome = "Make them scatter and flee! Any attack that inflicts at least 1 point of damage to hitpoints triggers a morale check for the opponent, as opposed to only if at or above 15 points of damage.",
	HeadHunter = "Go for the head! Gain [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] chance to hit the head for critical damage each time you hit the body. Bonus is reset upon hitting the head.",
	SunderingStrikes = "Effectiveness vs. Armor is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used.",
	BloodyHarvest = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit for all area of effect attacks.",
	FastAdaption = "Adapt to your opponent\'s moves! Gain an additional stacking [color=" + this.Const.UI.Color.PositiveValue + "]+8%[/color] chance to hit with each attack that misses an opponent. Bonus is reset upon landing a hit.",
	FullForce = "Put your full weight into every blow and gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] of your current body armor as additional maximum damage when attacking with melee attacks.",
	Weaponmaster = "All attacks cost [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] Fatigue to use and weapon condition degrades only half as fast. Dance gracefully with your weapon and make every hit count. ",
	CoupDeGrace = "Inflict additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] damage against targets that have sustained any injury effects, like a broken arm.",
	SteelBrow = "Hits to the head no longer cause critical damage to this character, which also lowers the risk of sustaining debilitating head injuries significantly.",
	Anticipation = "When being attacked with ranged weapons, gain [color=" + this.Const.UI.Color.PositiveValue + "]1 + 10% of your base Ranged Defense[/color] as additional Ranged Defense per tile that the attacker is away.",
	HoldOut = "Keep it together! Any negative status effect with a finite duration (e.g. Bleeding, Charmed) has its duration reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] turn, to a minimum of 1 turn.",
	Dodge = "Too fast for you! Gain [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] of the character\'s current Initiative as a bonus to Melee and Ranged Defense.",
	Nimble = "Specialize in light armor! By nimbly dodging or deflecting blows, convert any hits to glancing hits. Hitpoint damage taken is reduced by up to [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color], but lowered exponentially by the total penalty to Maximum Fatigue from body and head armor above 15. The lighter your armor and helmet, the more you benefit.\n\nBrawny does not affect this perk.\n\nDoes not affect damage from mental attacks or status effects, but can help to avoid receiving them.",
	BattleForged = "Specialize in heavy armor! Armor damage taken is reduced by a percentage equal to [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] of the current total armor value of both body and head armor. The heavier your armor and helmet, the more you benefit.\n\nDoes not affect damage from mental attacks or status effects, but can help to avoid receiving them.",
	DoubleStrike = "After landing a hit, the next attack does [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] damage to both hitpoints and armor. If the attack misses, the effect is wasted.",
	Vengeance = "After receiving a blow, the next attack of this character will inflict [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] damage to both hitpoints and armor. If the attack misses, the effect is wasted.",
	Duelist = "Become one with your weapon and go for the weak spots! With the offhand free, an additional [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] of any damage ignores armor. Does not work with two-handed weapons.",
	CripplingStrikes = "Cripple your enemies! Lowers the threshold to inflict injuries by [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] for both melee and ranged attacks.",
	QuickHands = "Looking for this? Swapping items in battle becomes a free action with no Action Point cost once every turn.",
	TrophyHunter = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] permanent hitpoint for every opponent slain.",
	Bruiser = "Effectiveness vs. Armor is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for any weapon used.",
	Crusher = "Put full force in your every blow! Shield damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+50%[/color] when using the Split Shield skill.",
	CloseCombatArcher = "If you can see the white in your enemy\'s eyes, aim for it! Damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+50%[/color] when using a ranged weapon (including throwing weapons) against a target 2 or less tiles away.",
	Bullseye = "Nailed it! The penalty to hitchance when shooting at a target you have no clear line of fire to is reduced from [color=" + this.Const.UI.Color.NegativeValue + "]75%[/color] to [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] for ranged weapons.",
	Ballistics = "The range penalty to hitchance is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] per tile.",
	Berserk = "RAAARGH! Once per turn, upon killing an enemy, [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Action Points are immediately regained. Characters can not regain more than their maximum Action Points and no more than 4 for a single attack.",
	Slaughterer = "Melee kills always are fatalities and have a [color=" + this.Const.UI.Color.NegativeValue + "]-15[/color] penalty to enemy Resolve checks. A gruesome display, enemies are more likely to suffer from hits to morale as their allies get carved up and split in two.",
	BetweenTheEyes = "The chance to hit the head for critical damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for all attacks.",
	BattleFlow = "Once per turn, killing an opponent reduces current fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] of the base maximum fatigue (before penalties due to armor are applied).",
	DevastatingStrikes = "All damage inflicted is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used. What could stand before you now?",
	KillingFrenzy = "Go into a killing frenzy! A kill increases all damage by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] for 2 turns. Does not stack, but another kill will reset the timer.",
	ShieldBash = "The Knock Back skill now also inflicts [color=" + this.Const.UI.Color.DamageValue + "]10 - 25[/color] Damage (50% effective against armor) and [color=" + this.Const.UI.Color.DamageValue + "]10[/color] Fatigue in addition to its normal effect, and costs 10 Fatigue less to use.",
	Brawny = "The fatigue and initiative penalty from wearing armor and helmet is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].",
	Stalwart = "Immunity against being knocked back or pulled up close. Applies to skills such as Knock Back, Hook and others that change a character\'s position.",
	Steadfast = "Getting hit by regular attacks does not cause a loss of fatigue anymore. Attacks that specifically target fatigue are unaffected.",
	Taunt = "Unlocks the \'Taunt\' skill which makes the targeted opponent take offensive actions instead of defensive ones, and attack the taunting character over another, potentially more vulnerable one.",
	Colossus = "Bring it on! Hitpoints are increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color], which also reduces the chance to sustain debilitating injuries when being hit.",
	Deflect = "Learn to better deflect hits to the side instead of blocking them head on. Shield damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color] to a minimum of 1.",
	Evade = "A moving target is an elusive one. On getting hit with a ranged attack, there is a [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] chance to only take a gracing hit and suffer only [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] of the normal damage.",
	ShieldExpert = "Learn to better deflect hits to the side instead of blocking them head on.\n\nThe shield defense bonus is increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]. This also applies to the additional defense bonus of the Shieldwall skill.\n\nShield damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] to a minimum of 1.\n\nThe \'Knock Back\' skill gains [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] chance to hit.",
	NineLives = "Once per battle, upon receiving a killing blow, survive instead with a few hitpoints left. The next hit is likely to kill you for good, of course.",
	BatteringRam = "Immunity against being stunned.",
	LastStand = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1%[/color] additional Melee and Ranged Defense for every 1% of hitpoints missing.",
	Ironside = "All damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-5%[/color] for every opponent adjacent and in melee range, up to a [color=" + this.Const.UI.Color.NegativeValue + "]-30%[/color] total damage reduction.",
	BagsAndBelts = "Unlock two extra bag slots to carry all your favorite things. Items placed in bags no longer give a penalty to Maximum Fatigue, except for two-handed weapons and shields.",
	Rebound = "Fatigue regeneration is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] per turn.",
	Feint = "If an attack misses, it costs [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] less fatigue than normal.",
	Student = "Everything can be learned if you put your mind to it. Gain additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] experience from battle. At the eleventh character level, you gain an additional perk point and this perk becomes inert.",
	Gifted = "Mercenary life comes easy when you\'re naturally gifted. Instantly gain a levelup to increase this character\'s attributes with maximum rolls, but without talents.",
	Lookout = "Learn to find your enemies before they find you. Vision is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	Zweihander = "Fatigue costs for all two-handed weapon skills are reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "Learn to move on difficult terrain. Action Point costs for movement on all terrain is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] to a minimum of 2 Action Points per tile, and Fatigue cost is reduced to half. Changing height levels also has no additional Action Point cost anymore.",
	FortifiedMind = "An iron will is not swayed from the true path easily. Resolve is increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color].",
	Captain = "Use a sergeant on the battlefield as an extension of your leadership and to keep everyone in line. Allies at a range of 5 tiles or less will get [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] of this character\'s Resolve as a bonus added to their own, up to a maximum of this character\'s Resolve.\n\nDoes not stack; the sergeant with the highest Resolve will apply the bonus.",
	BoondockBlade = "When in a hiding place, such as high grass, gain a bonus of [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] to Melee Skill, Ranged Skill, and Melee and Ranged Defense.",
	ArtfulDodger = "Zone of Control is ignored when moving away from enemy combatants in melee.",
	InspiringPresence = "A great leader of men inspires his followers to overcome their limits. Allies start every battle at confident morale unless prohibited by character traits.",
	Inspire = "Unlocks the \'Inspire\' skill which can push allies to go beyond their limits, granting them additional Action Points.",
	Underdog = "I\'m used to it. The defense malus due to being surrounded by opponents no longer applies to this character. If an attacker has the Backstabber perk, the effect of that perk is negated, and the normal defense malus due to being surrounded is applied instead.",
	Sprint = "Unlocks the \'Sprint\' skill which allows for sprinting over short distances in straight lines instantly.",
	Recover = "Unlocks the \'Recover\' skill which allows for resting a turn in order to reduce accumulated Fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	FirstMove = "Always act first in the very first round of combat, before any of your opponents do.",
	Backstabber = "Honor doesn\'t win you fights, stabbing the enemy where it hurts does. The bonus to hitchance in melee is doubled to [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for each ally surrounding and distracting your target.",
	LoneWolf = "I work best alone. With no ally within 3 tiles of distance, gain a [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] bonus to Melee Skill, Ranged Skill, Melee Defense, Ranged Defense, and Resolve.",
	ReachAdvantage = "Learn to use the superior reach of large weapons to keep the enemy from getting close enough to land a good hit.\n\nEach hit with a two-handed melee weapon adds a stack of Reach Advantage that increases your Melee Defense by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color], up to a maximum of 5 stacks, until this character\'s next turn. A single attack hitting multiple targets can add several stacks at once.\n\nIf you put away your weapon, you lose all stacks.",
	Overwhelm = "Learn to take advantage of your high Initiative and prevent the enemy from attacking effectively by overwhelming them with your attacks!\n\nWith every attack, hit or miss, against an opponent that acts after you in the current round, inflict the \'Overwhelmed\' status effect which lowers both Melee Skill and Ranged Skill by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] for one turn.\n\nThe effect stacks with each attack, and can be applied to multiple targets at once with a single attack.",
	SpecBow = "Master the art of archery and pelting your opponents with arrows from afar. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nView range and maximum firing range with bows is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	SpecCrossbow = "Master crossbows and learn where to aim best. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nAn additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] of damage inflicted with crossbows ignores armor.",
	SpecThrowing = "Master throwing weapons to wound or kill the enemy before they even get close. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nDamage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]40%[/color] when attacking at 2 tiles of distance.\n\nDamage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] when attacking at 3 tiles of distance.",
	SpecAxe = "Master combat with axes and destroying shields. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nSplit Shield damage to shields is increased by [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] when used with axes.\n\nRound Swing gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.\n\nThe Longaxe no longer has a penalty for attacking targets directly adjacent.",
	SpecCleaver = "Master cleavers to inflict gruesome wounds. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nBleeding damage inflicted by cleavers is doubled to [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] per turn.",
	SpecDagger = "Master swift and deadly daggers. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nStab and Puncture have a reduced Action Point cost to allow for an additional attack each turn.",
	SpecSword = "Master the art of swordfighting and using your opponent\'s mistakes to your advantage. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nRiposte no longer has a penalty to hitchance.\n\nSplit and Swing gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.",
	SpecSpear = "Master fighting with spears and keeping the enemy at bay. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nSpearwall is no longer disabled once an opponent manages to overcome it. Instead, Spearwall continues to give free attacks on any further opponent attempting to enter the Zone of Control.\n\nThe Spetum no longer has a penalty for attacking targets directly adjacent.",
	SpecPolearm = "Master polearms and keeping the enemy at bay. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nPolearm skills have their Action Point cost reduced to [color=" + this.Const.UI.Color.NegativeValue + "]5[/color], and no longer have a penalty for attacking targets directly adjacent.",
	SpecHammer = "Master hammers and fighting against heavily armored opponents. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nDestroy Armor and Demolish Armor inflict [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] more damage against armor.\n\nShatter gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.\n\nThe Polehammer no longer has a penalty for attacking targets directly adjacent.",
	SpecMace = "Master maces to beat your opponents into submission, armored or not. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nKnock Out and Strike Down have a [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] chance to stun the target if not immune.",
	SpecFlail = "Master flails and circumvent your opponent\'s shield. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nLash and Hail ignore the defense bonus of shields.\n\nThresh gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.",

	vazl_ValaInscriptionMastery = "Lowers the cooldown until the Vala can begin inscribing items again (after a successful inscription) from 20 to [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] days, and increases her inscription speed.",
	vazl_ValaInscribeWeapon = "Allows the Vala to inscribe any weapon currently equipped by anyone in the company with a random rune sigil.\n\nPossibilities: aiming, feeding, power\n\nUpon success, she needs to wait 20 days before she can begin inscribing weapons again.",
	vazl_ValaInscribeHelmet = "Allows the Vala to inscribe any helmet currently equipped by anyone in the company with a random rune sigil.\n\nPossibilities: bravery, clarity, luck\n\nUpon success, she needs to wait 20 days before she can begin inscribing helmets again.",
	vazl_ValaInscribeArmor = "Allows the Vala to inscribe any armor currently equipped by anyone in the company with a random rune sigil.\n\nPossibilities: endurance, resilience, safety\n\nUpon success, she needs to wait 20 days before she can begin inscribing armors again.",
	vazl_ValaInscribeShield = "Allows the Vala to inscribe any shield currently equipped by anyone in the company with a random rune sigil.\n\nPossibilities: none\n\nUpon success, she needs to wait 20 days before she can begin inscribing shields again."
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "Click to focus party",
		Hint_FocusLocation = "Click to focus location"
	},
	Tactical = {
		Hint_FocusCharacter = "Click to focus character",
		Hint_CannotChangeItemInCombat = "Can not be changed in combat",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "Only the character whose turn it is right now can change items"
	}
};
