local gt = this.getroottable();

if (!("Strings" in gt.Const))
{
	gt.Const.Strings <- {
		function getArticle( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "an " : "a ";
		}

		function getArticleCapitalized( _object )
		{
			return this.isFirstCharacter(_object, [
				"A",
				"E",
				"I",
				"O",
				"U"
			]) ? "An " : "A ";
		}

	};
}

if (!("Tactical" in gt.Const.Strings))
{
	gt.Const.Strings.Tactical <- {};
}

if (!("World" in gt.Const.Strings))
{
	gt.Const.Strings.World <- {};
}

gt.Const.Strings.Quantity <- [
	"1st",
	"2nd",
	"3rd",
	"4th",
	"5th",
	"6th",
	"7th",
	"8th",
	"9th",
	"10th",
	"11th",
	"12th",
	"13th",
	"14th",
	"15th",
	"16th",
	"17th",
	"18th",
	"19th",
	"20th"
];
gt.Const.Strings.Difficulty <- [
	"Beginner",
	"Veteran",
	"Expert",
	"Legendary"
];
gt.Const.Strings.EntityName <- [
	"Necromancer",
	"Wiederganger",
	"Armored Wiederganger",
	"Fallen Hero",
	"Rachegeist",
	"Ancient Auxiliary",
	"Ancient Legionary",
	"Ancient Honor Guard",
	"Ancient Priest",
	"The Conqueror",
	"Necrosavant",
	"Geist",
	"Nachzehrer",
	"Orc Young",
	"Orc Berserker",
	"Orc Warrior",
	"Orc Warlord",
	"Militia",
	"Militia Marksman",
	"Militia Veteran",
	"Militia Captain",
	"Bounty Hunter",
	"Peasant",
	"Caravan Hand",
	"Caravan Guard",
	"Caravan Cart",
	"Footman",
	"Zweihander",
	"Billman",
	"Arbalester",
	"Standard Bearer",
	"Sergeant",
	"Knight",
	"Donkey",
	"Brigand Thug",
	"Brigand Poacher",
	"Brigand Marksman",
	"Brigand Raider",
	"Brigand Leader",
	"Goblin Ambusher",
	"Goblin Skirmisher",
	"Goblin Overseer",
	"Goblin Shaman",
	"Goblin Wolfrider",
	"Wolf",
	"Wardog",
	"Armored Wardog",
	"Mercenary",
	"Mercenary",
	"Swordmaster",
	"Hedge Knight",
	"Master Archer",
	"Greenskin Catapult",
	"Cultist",
	"Direwolf",
	"Lindwurm",
	"Unhold",
	"Unhold",
	"Unhold",
	"Webknecht",
	"Webknecht Eggs",
	"Alp",
	"Hexe",
	"Schrat",
	"Sapling",
	"Wildman",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayer",
	"Nightmare",
	"Barbarian Thrall",
	"Barbarian Reaver",
	"Barbarian Chosen",
	"Barbarian Drummer",
	"Barbarian Beastmaster",
	"Armored Unhold",
	"Armored Unhold",
	"Barbarian King",
	"Warhound",
	"The Ijirok",
	"Barbarian Madman",
	"Bandit Rabble",
	"Cat",
	"Orc Elite",
	"Orc Behemoth",
	"White Direwolf",
	"Skin Ghoul",
	"Stollwurm",
	"Rock Unhold",
	"Redback Spider",
	"Demon Alp",
	"Hexe Coven Leader",
	"Heartwood Schrat",
	"Heartwood Sapling",
	"White Warwolf"

];
gt.Const.Strings.EntityNamePlural <- [
	"Necromancers",
	"Wiedergangers",
	"Armored Wiedergangers",
	"Fallen Heroes",
	"Rachegeists",
	"Ancient Auxiliaries",
	"Ancient Legionaries",
	"Ancient Honor Guards",
	"Ancient Priests",
	"The Conqueror",
	"Necrosavants",
	"Geists",
	"Nachzehrers",
	"Orc Young",
	"Orc Berserkers",
	"Orc Warriors",
	"Orc Warlords",
	"Militia",
	"Militia Marksmen",
	"Militia Veterans",
	"Militia Captains",
	"Bounty Hunters",
	"Peasants",
	"Caravan Hands",
	"Caravan Guards",
	"Caravan Carts",
	"Footmen",
	"Zweihanders",
	"Billmen",
	"Arbalesters",
	"Standard Bearers",
	"Sergeants",
	"Knights",
	"Donkeys",
	"Brigand Thugs",
	"Brigand Poachers",
	"Brigand Marksmen",
	"Brigand Raiders",
	"Brigand Leaders",
	"Goblin Ambushers",
	"Goblin Skirmishers",
	"Goblin Overseers",
	"Goblin Shamans",
	"Goblin Wolfriders",
	"Wolves",
	"Wardogs",
	"Armored Wardogs",
	"Mercenaries",
	"Mercenaries",
	"Swordmasters",
	"Hedge Knights",
	"Master Archers",
	"Greenskin Catapults",
	"Cultists",
	"Direwolves",
	"Lindwurms",
	"Unholds",
	"Unholds",
	"Unholds",
	"Webknechts",
	"Webknecht Eggs",
	"Alps",
	"Hexen",
	"Schrats",
	"Saplings",
	"Wildmen",
	"Kraken",
	"Irrlicht",
	"Fallen Betrayers",
	"Nightmares",
	"Barbarian Thralls",
	"Barbarian Reavers",
	"Barbarian Chosen",
	"Barbarian Drummers",
	"Barbarian Beastmasters",
	"Armored Unholds",
	"Armored Unholds",
	"Barbarian Kings",
	"Warhounds",
	"Beasts of Winter",
	"Barbarian Madmen",
	"Bandit Rabble",
	"Cats",
	"Orc Elites",
	"Orc Behemoths",
	"White Direwolves",
	"Skin Ghouls",
	"Stollwurmer",
	"Rock Unholds",
	"Redback Spiders",
	"Demon Alps",
	"Hexe Coven Leaders",
	"Heartwood Schrats",
	"Heartwood Saplings",
	"White Warwolves"
];
gt.Const.Strings.Tactical.EntityName <- {
	Boulder = "Boulder",
	Shrubbery = "Shrubbery",
	Tree = "Tree",
	Brush = "Brush",
	Cartwheel = "Old Cartwheel",
	RuinedPillar = "Ruined Pillar",
	Cart = "Caravan Cart",
	Donkey = "Donkey"
};
gt.Const.Strings.Tactical.EntityDescription <- {
	Boulder = "A large stone boulder. Blocks movement and line of sight.",
	Shrubbery = "Very dense shrubbery that blocks movement and line of sight.",
	Tree = "A large tree with a massive trunk.",
	TreeSwamp = "This tree is rotten and long dead.",
	TreeTrunk = "A treetrunk half covered in foul water.",
	Brush = "Very dense shrubbery that blocks movement and line of sight.",
	Cartwheel = "The old and broken wheel of an oxcart.",
	RuinedPillar = "TODO",
	Cart = "A cart full of trading goods.",
	Donkey = "A donkey used for pulling heavy carts."
};
gt.Const.Strings.ShipNames <- [
	"Summer Daze",
	"Merry Mist",
	"Howl of the Sea",
	"Coral Secret",
	"Sandy Bay",
	"Lady of the Sea",
	"Solitaire",
	"Brunhild",
	"Mathilda",
	"Comet",
	"Tetrarch",
	"Lofjord",
	"Autumn Wind",
	"Poundmaker",
	"Brakel",
	"Seven Stars",
	"Dark Omen",
	"Concord",
	"Albatros",
	"Golden Horse",
	"Sea Nymph",
	"Twisted Fate",
	"King\'s Bounty",
	"Bald Monk",
	"Golden Sun",
	"Vanity",
	"Brazen",
	"Tiger\'s Claw",
	"Sycamore",
	"Noble Runner",
	"Bleak Moon",
	"Clansman",
	"Whale\'s Voyage",
	"Quickmatch",
	"Blackfly",
	"Ejnar Erikson",
	"Lindwurm",
	"Supreme",
	"Griffon",
	"Axford",
	"Bertha",
	"Seagull",
	"Belzebub"
];
gt.Const.Strings.MercenaryCompanyNames <- [
	"Iron Ravens",
	"Golden Order",
	"Swords of the South",
	"Wolves of Bleak Forest",
	"Black Shields",
	"Iron Crown Company",
	"Radobrecht\'s Swords",
	"Whistling Arrows",
	"Azure Boars",
	"Fang and Coin",
	"Red Legion",
	"Hungry Hounds",
	"Crimson Daggers",
	"King\'s End Company",
	"Black Company",
	"Second Sons",
	"Walther\'s Fellowship",
	"Grudgebringers",
	"Bernhard\'s Bears",
	"Silver Claw",
	"Iron Brotherhood",
	"Orcbane Company",
	"Iron Covenant",
	"Unbroken Third",
	"Dogs of War",
	"Falkenberg\'s Legion",
	"Free Men",
	"Lords of War",
	"Northern Company",
	"Forsaken Returned",
	"White Company",
	"Widowmakers",
	"Cold Hearts Company",
	"Burning Sun Company",
	"Chosen Few",
	"Dead Men",
	"Bronzeheads",
	"Markland Pikes",
	"Hammerguard",
	"Crowntakers",
	"Silverreach Spears",
	"The Iron Pact",
	"The Blood Bound",
	"The Bulwark",
	"Dawn\'s March",
	"Sons of Winter",
	"Company of the River House",
	"Flaming Comet Company",
	"The Grand Company",
	"Rightful Ravagers",
	"The Host",
	"Forsaken Brigade",
	"Battle\'s Chosen",
	"Bringers of Peace",
	"Shields of the Night",
	"The Mongrels",
	"The Bone Wardens",
	"Lost Legion"
];
gt.Const.Strings.NobleHouseNames <- [
	"Grimmund",
	"Weilburg",
	"Armsberg",
	"Gota",
	"Eisenstein",
	"Grauwall",
	"Rabenholt",
	"Sommerwein",
	"Winterhall",
	"Ruhmolt",
	"Adelreich",
	"Perowinger",
	"Eiglof",
	"Berengar",
	"Gunbald",
	"Goswin",
	"Adelheim",
	"Ammondt",
	"Bartholin",
	"Eberlin",
	"Folsach",
	"Hedin",
	"Horn",
	"Niedergard",
	"Rosenving",
	"Thurah",
	"Kaltenborn",
	"Krieger",
	"Steinwall",
	"Harkon",
	"Osten"
];
gt.Const.Strings.BusinessReputation <- [
	"Treacherous",
	"Incompetent",
	"Unreliable",
	"Unknown",
	"Recognized",
	"Reliable",
	"Competent",
	"Professional",
	"Reputable",
	"Famed",
	"Great",
	"Glorious",
	"Fabled",
	"Legendary",
	"Invincible",
	"Immortal"
];
gt.Const.Strings.MoralReputation <- [
	"Dreaded",
	"Cruel",
	"Merciless",
	"Notorious",
	"Neutral",
	"Neutral",
	"Kind",
	"Good",
	"Chivalrous",
	"Saintly"
];
gt.Const.Strings.Relations <- [
	"Hostile",
	"Threatening",
	"Unfriendly",
	"Cold",
	"Neutral",
	"Neutral",
	"Open",
	"Friendly",
	"Very Friendly",
	"Allied"
];
gt.Const.Strings.Tactical.TerrainName <- [
	"None",
	"Dirt Road",
	"Clay Road",
	"Cobblestone Road",
	"Grassland",
	"Dirt",
	"Forest",
	"Muddy Earth",
	"Plashy Grass",
	"Murky Water",
	"Steppe",
	"Dry Steppe",
	"Tundra",
	"Snow",
	"Light Snow",
	"Stone",
	"Stone"
];
gt.Const.Strings.Tactical.TerrainDescription <- [
	"None",
	"A dirt road originating from constant use by humans and animals.",
	"A primitve road consisting of tamped clay.",
	"A cobblestone road used for carriages and larger vehicles.",
	"Short grass on flat and solid ground.",
	"Bare and flat earth with barely any vegetation.",
	"Forest ground covered in a thick and soft mossy layer.",
	"Dark and muddy earth.",
	"Mostly firm ground covered in tall and soft grass.",
	"Shallow, murky water covering a soft and muddy ground.",
	"Flat and firm ground covered with dry and shriveled grass.",
	"Hard patches of earth completely dried out by sun and heat.",
	"Flat and arid ground covered in rough grasses and weeds.",
	"Frozen ground covered in a thick layer of snow.",
	"Frozen ground covered in a light layer of snow.",
	"Smooth stone ground granting a good footing.",
	"TODO"
];
gt.Const.Strings.UI <- {
	Introduction = "You soak in the cool morning air. As the sun slowly rises, so does a new chapter in your life begin. After years of bloodying your sword for meager pay you\'ve saved up enough crowns to start your very own mercenary company. With you are %allbrothers% with whom you\'ve fought before side by side in the shieldwall. You are their commander now, the leader of the %companyname%.\n\nAs you travel the lands you should hire new men in the villages and cities to fill your ranks. Many who offer their services will have never picked up a real weapon before. Maybe they are desperate, maybe they are greedy for quick spoils of war. Most of them will die on the battlefield. But do not be discouraged. Such is the mercenary life, and the next village will always have new men eagerly looking for a new start in life.\n\nThe lands are dangerous these times. Robbers and pillagers lay in ambush by the roads, wild beasts roam the dark forests and orc tribes are restless in the swamps to the east. There are rumors even of dark magic being at work, the dead rising from their graves and walking again. There is plenty of opportunity to earn good money, whether by taking on contracts you can find in the villages, cities and strongholds all over the land, or by venturing out on your own to explore and raid.\n\nYour men look to you to give a command. They live and die for the %companyname% now.\n\n[color=#bd9d71]EARLY ACCESS DISCLAIMER: This version is still heavily work in progress and does not represent the final quality of the product. Features may be incomplete or missing, the UI is unskinned as of yet, there will be bugs, and the balancing and progression of the economy, resources and enemies may need tweaking and can be too challenging or easy occasionally. A lot of additional content will be added over the course of the Early Access, including more enemies, items, contracts, terrain types, unique locations, story events and other features.[/color]",
	FleeDialogueConsequences = "Sometimes it\'s better to do a tactical retreat in order to live and fight another day. The men will attempt to reach the edges of the map by themselves and then safely retreat. However, the enemy may catch up, and anyone currently engaged may not be able to get away unscathed or even alive.",
	RetreatDialogueConsequences = "The enemy is battered and beaten. Those few still alive scatter away in all directions. Will you hunt them down to claim their heads and possessions, or declare the battle won?"
};
gt.Const.Strings.AlpStateName <- [
	"",
	"Existing partly in dreams",
	"Existing partly in dreams",
	"Existing mostly in dreams",
	"Existing mostly in dreams"
];
gt.Const.Strings.BodyPartName <- [
	"body",
	"head"
];
gt.Const.Strings.ItemSlotName <- [
	"Body",
	"Head",
	"Mainhand",
	"Offhand",
	"Accessory",
	"Bag"
];
gt.Const.Strings.World.TimeOfDay <- [
	"Dawn",
	"Morning",
	"Midday",
	"Afternoon",
	"Evening",
	"Dusk",
	"Night",
	"Dawn"
];
gt.Const.Strings.Direction <- [
	"north",
	"north-east",
	"south-east",
	"south",
	"south-west",
	"north-west",
	"<undefined>"
];
gt.Const.Strings.Direction8 <- [
	"north",
	"north-east",
	"east",
	"south-east",
	"south",
	"south-west",
	"west",
	"north-west"
];
gt.Const.Strings.Terrain <- [
	"",
	"in the ocean",
	"on the plains",
	"in the swamps",
	"on the hills",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the forest",
	"in the mountains",
	"",
	"",
	"in the snow",
	"in the wastelands",
	"in the tundra",
	"in the steppe",
	"on the shore"
];
gt.Const.Strings.TerrainShort <- [
	"",
	"bay",
	"plains",
	"swamp",
	"hills",
	"forest",
	"forest",
	"forest",
	"forest",
	"mountain",
	"",
	"",
	"snow",
	"wastelands",
	"tundra",
	"steppe",
	"shore"
];
gt.Const.Strings.TerrainRegionNames <- [
	[],
	[
		"Stormy Sea",
		"Kraken\'s Refuge",
		"White Horses Sea",
		"Thousand Gulls Sea",
		"Deep Depths",
		"Rainy Ocean",
		"Unbound Ocean",
		"Tempest Ocean",
		"Thunder Sea",
		"Great Sea",
		"Surging Sea",
		"Pearl Sea",
		"Howling Sea",
		"Cruel Sea",
		"Arching Tides Ocean",
		"Whispering Waves Sea",
		"Soft Ripple Sea",
		"Green Sea",
		"Sea of Turning Tides",
		"Wailing Ocean",
		"Foamy Shallows",
		"Murky Tide Ocean",
		"Shimmering Expanse",
		"Azure Expanse",
		"The Raging Gulf",
		"The Shimmering Depths"
	],
	[
		"Vendland",
		"Speedwell Fields",
		"Plainshire",
		"Vinland",
		"Lowlands",
		"Windlands",
		"Wide Watch",
		"Glaucious Domain",
		"Rich Meadows",
		"Markland",
		"Fast Clouds County",
		"Fairdale",
		"Fleetfeet\'s Range",
		"Wanderer\'s Boon",
		"Valeshire",
		"Ridland",
		"Greenfold",
		"Hogfolk",
		"Durum",
		"Shallowford",
		"Two Fields",
		"Kingmill",
		"Minceacre",
		"Glendale",
		"Brillfold",
		"Kindon",
		"Greenmere",
		"Mooseridge",
		"Altmark",
		"Neumark",
		"Fair Range",
		"Middlemark",
		"Grasslands",
		"Moss Valley",
		"Wideacre",
		"Southbloom",
		"Dawnland",
		"Oak Wood Meadows",
		"Southwind Acres",
		"Meadowcove",
		"Willow\'s Fields",
		"Grand View Pastures",
		"Nightingale Valley",
		"Silversage Fields",
		"Heartsong\'s Range"
	],
	[
		"Black Marshes",
		"Dead Ponds",
		"Tar Fields",
		"Peatfold",
		"Suffocating Bog",
		"Eerie Marshes",
		"Black Morass",
		"Sticky Wallow",
		"Dreaded Mire",
		"Murky Swamplands",
		"Mortun",
		"Blackfan",
		"Gallowsbog",
		"Dungslump",
		"Houndsmarsh",
		"Shipreath Marsh",
		"Cursed Lands",
		"Grimdowns",
		"The Reeds",
		"Froghold",
		"Spidergrove",
		"Duke\'s Demise",
		"Bottomless Pits",
		"Poisonbreath Marshes",
		"Froglickers Grove",
		"Deadbottom",
		"The Wetlands",
		"The Marshlands",
		"Black Mud",
		"Desolate Moor",
		"Black Fumes Polder",
		"Endless Polder",
		"Peat Basin",
		"Riverland Glades",
		"Southland Bowels",
		"Azure Marsh",
		"Thousand Mirrors Bog",
		"The Narrow Quag",
		"Glades of Decay",
		"Ashen Wetlands",
		"Savage Bog",
		"Mire of the Whisp",
		"Forbidden Waters",
		"Dreadmoor"
	],
	[
		"Bonefold Barrow",
		"Knight\'s Axe Hills",
		"Skullsbreath Mound",
		"Ancient Knolls",
		"Oldlock Hills",
		"The Hummocks",
		"Knowesfold",
		"Ancient Cairns",
		"Humming Hills",
		"Sharp Rocks",
		"Misty Barrows",
		"Boulderhills",
		"Scree Barrows",
		"Bed Load Knolls",
		"Ghost Hills",
		"Banshee Mounds",
		"Shinglehumps",
		"Earthwatch Hills",
		"Giant\'s Pebbles",
		"Buried Snake Hills",
		"Skullslide Hills",
		"Rustcave Hills",
		"Witchmount Hills",
		"Juniper Hills",
		"White Goat Mounds",
		"Barum",
		"The Reach",
		"Whispering Hills",
		"The Bronze Hills",
		"Willowshire Hillside",
		"The Scarlet Hills",
		"Giant\'s Slopes",
		"The Gloomy Hills",
		"The Collapsing Hills"
	],
	[
		"Bleak Forest",
		"Dire Woods",
		"Dismal Woods",
		"Dusky Forest",
		"Scoundrels\' Forest",
		"Boar Woods",
		"Bandit\'s Rest",
		"Splinterdale",
		"Spiderwood",
		"Tickbrake",
		"Druid\'s Grove",
		"Brittle Branch Woods",
		"White Wolf\'s Home",
		"Ravenhold",
		"Needlegrove",
		"Rustling Thicket",
		"Mossy Pine Woods",
		"Crows Nest",
		"Black Forest",
		"Prowlers Woods",
		"Gloomy Woods",
		"Wolfwood",
		"Black Woods",
		"Murmuring Woods",
		"Dark Thorn Wilds",
		"Hedgehog Thicket",
		"Misty Covert",
		"Borderdale",
		"Temple Grove",
		"Wretched Woods",
		"Elder Woods",
		"Deep Covert",
		"Macaw Woods",
		"Hexenwald"
	],
	[],
	[
		"Ancient Forest",
		"Ranger\'s Rest",
		"Valley of the Deer",
		"Oldgrowth",
		"Rampants",
		"Ironoak Grove",
		"Hunter\'s Bosk",
		"Royal Grounds",
		"Sylvan Woods",
		"Fox and Hare Woods",
		"Snapping Twig Forest",
		"Antlerfold",
		"Old Forest",
		"Greenwood Forest",
		"Mossy Woods",
		"Misty Woods",
		"The Sea of Trees",
		"Timberland",
		"Whispering Groves",
		"Grand Hare Woods",
		"Chestnut Grove",
		"Snake\'s Covert",
		"Blackwood Forest",
		"Stormy Woods",
		"Rustling Thicket",
		"Wicked Woods",
		"Gray Toad Woodlands",
		"Treewalker Woodlands",
		"Jagged Woods",
		"Stag\'s Grounds",
		"Crowned Oak Forest",
		"Elderberry Woods",
		"Elm Grove",
		"Black Mole Woods",
		"Brookwood",
		"Springwood",
		"Everwoods"
	],
	[
		"Red Worm Woods",
		"Fiery Woods",
		"Smoldering Woods",
		"Ember Forest",
		"Vibrant Grove",
		"Foxfold Forest",
		"Somerhurst",
		"Fireander",
		"Bloodcut Growth",
		"Burnend",
		"Rustdroop",
		"Blood Woods",
		"Blazing Forest",
		"Vermillion Woods",
		"Crimson Forest",
		"Auburn Woods",
		"Redwood",
		"Badger\'s Covert",
		"Birch Timberland",
		"Waterwood Forest",
		"Pyrewood",
		"Beatroot Wilds",
		"Bogwood Grove",
		"Yellowleaf\'s Range",
		"Bloodbloom Woods",
		"Redbark Forest",
		"Firerock Grove"
	],
	[
		"Spine of the World",
		"Sleeping Giants Back",
		"Jagged Spires",
		"Wall of the Gods",
		"Dreaded Rocks",
		"Rocky Ridge",
		"Jagged Summit",
		"Silver Ridge",
		"Misty Summit",
		"Iron Mountains",
		"Goathorns",
		"Dragonteeth",
		"Highrise",
		"Eagleflight",
		"Grimroof",
		"Dunspike",
		"Dreadhorn",
		"Ravensbeak",
		"Mount Bulkhead",
		"Bulwark",
		"Cloddheads",
		"Browslopes",
		"Hero\'s Fall",
		"Yawning Gaps",
		"Mammothshoulders",
		"Swellpike Heights",
		"Bald Crown",
		"Cloudcrest",
		"Evermist Mountains",
		"Slaughtermount",
		"The Rift",
		"The Thundering Peaks",
		"Decayed Heights",
		"The Glistening Heights",
		"Deserted Rise",
		"The Vast Rise",
		"Moonlit Peaks",
		"The Ashen Pinnacle",
		"The Bare Peaks",
		"The Shadow Mountains",
		"Grimestone Peaks",
		"Brimstone Shoulders",
		"Iron Peaks"
	],
	[],
	[],
	[
		"White Waste",
		"Frozen Plains",
		"Sea of Snow",
		"White Wilderness",
		"Silver Plains",
		"Howling Wastes",
		"Silver Flats",
		"Everwinter",
		"Frozen North",
		"World\'s Rim",
		"Coldend",
		"Wintermore",
		"Icemark",
		"Spikewind",
		"Iceblade Dale",
		"Silversand Hold",
		"Frostfold",
		"Icehenge",
		"Frozen Burrows",
		"Aurora Flats",
		"Frostfinger\'s Realm",
		"Nevermelting Hold",
		"The Pale Expanse",
		"Desert of Mirrors",
		"The Ghostly Plains",
		"Chillwind Flatlands",
		"The Glazed Valley",
		"The Howling Desert",
		"The Powder Plains",
		"Snowbank"
	],
	[],
	[
		"Northmark",
		"Tablelands",
		"Scragglands",
		"Norshire",
		"Barescrub",
		"Forefathers\' Highlands",
		"Skyreach",
		"Clan\'s Claim",
		"Rugged Flats",
		"Northern Clanlands",
		"Ragwilds",
		"Barrens",
		"Ragnar\'s Range",
		"Pagan Heathland",
		"Ruffmuir",
		"Windlands",
		"Angbride",
		"Baleford",
		"Bleakwolds",
		"Nordlands",
		"Glenmore Barrows",
		"Woldwich",
		"Kinmere",
		"Northurst",
		"Norenford",
		"Holmburn",
		"The Dreary Barrens"
	],
	[
		"Scrublands",
		"Drylands",
		"Torched Plains",
		"Red Lowlands",
		"Scorching Shire",
		"Golden Valley",
		"Southern Steppe",
		"Southmark",
		"The Scald",
		"Bleached Bone Dale",
		"Droughtshire",
		"Sunpan",
		"The Dryweeds",
		"Thornvale",
		"Bronze Flats",
		"Dire Hold",
		"Parcheim",
		"Smallriver Hold",
		"Razorshrub",
		"Gnarlheim",
		"Gritstone",
		"Suderos",
		"Suderland",
		"Solsweald",
		"Rustyblade Mesa",
		"Muskena",
		"Solstein",
		"Southwatch",
		"Sunreach",
		"Sandshear",
		"Skauna",
		"Caskain",
		"Maraman",
		"Jundland",
		"The Borderlands"
	],
	[]
];
gt.Const.Strings.Distance <- [
	"close by",
	"not far",
	"some way",
	"a long way",
	"far",
	"far away"
];
gt.Const.Strings.PartyStrength <- [
	"Puny",
	"Weak",
	"Average",
	"Strong",
	"Dangerous",
	"Deadly",
	"Invincible"
];
gt.Const.Strings.EngageEnemyNumbers <- [
	"A few",
	"Some",
	"Many",
	"Lots of",
	"A plethora of"
];
gt.Const.Strings.PerkName <- {
	TrophyHunter = "Trophy Hunter",
	Bruiser = "Bruiser",
	Crusher = "Crusher",
	CloseCombatArcher = "Close Combat Archer",
	Bullseye = "Bullseye",
	Ballistics = "Balistics",
	Berserk = "Berserk",
	Slaughterer = "Slaughterer",
	BetweenTheEyes = "Between the Eyes",
	DevastatingStrikes = "Devastating Strikes",
	KillingFrenzy = "Killing Frenzy",
	ShieldBash = "Shield Bash",
	Brawny = "Brawny",
	Stalwart = "Stalwart",
	Taunt = "Taunt",
	Steadfast = "Steadfast",
	Colossus = "Colossus",
	Deflect = "Deflect",
	Evade = "Evade",
	ShieldExpert = "Shield Expert",
	NineLives = "Nine Lives",
	BatteringRam = "Battering Ram",
	LastStand = "Last Stand",
	Ironside = "Ironside",
	BattleForged = "Battle Forged",
	BagsAndBelts = "Bags and Belts",
	Rebound = "Rebound",
	Feint = "Feint",
	Student = "Student",
	Lookout = "Lookout",
	Zweihander = "Zweihander",
	Pathfinder = "Pathfinder",
	FortifiedMind = "Fortified Mind",
	Captain = "Sergeant",
	BoondockBlade = "Boondock Blade",
	ArtfulDodger = "Artful Dodger",
	InspiringPresence = "Inspiring Presence",
	QuickHands = "Quick Hands",
	CripplingStrikes = "Crippling Strikes",
	Duelist = "Duelist",
	Vengeance = "Vengeance",
	DoubleStrike = "Double Strike",
	Nimble = "Nimble",
	Dodge = "Dodge",
	HoldOut = "Resilient",
	Anticipation = "Anticipation",
	SteelBrow = "Steel Brow",
	CoupDeGrace = "Executioner",
	Weaponmaster = "Weaponmaster",
	FullForce = "Full Force",
	FastAdaption = "Fast Adaptation",
	BloodyHarvest = "Bloody Harvest",
	SunderingStrikes = "Sundering Strikes",
	BattleFlow = "Battle Flow",
	HeadHunter = "Head Hunter",
	RallyTheTroops = "Rally the Troops",
	Fearsome = "Fearsome",
	Indomitable = "Indomitable",
	Furor = "Furor",
	Debilitate = "Debilitate",
	Footwork = "Footwork",
	Rotation = "Rotation",
	PerfectFocus = "Perfect Focus",
	ReturnFavor = "Return Favor",
	Underdog = "Underdog",
	Sprint = "Sprint",
	Recover = "Recover",
	Inspire = "Inspire",
	Gifted = "Gifted",
	FirstMove = "First Move",
	FirstAid = "First Aid",
	Adrenalin = "Adrenaline",
	Backstabber = "Backstabber",
	LoneWolf = "Lone Wolf",
	ReachAdvantage = "Reach Advantage",
	Overwhelm = "Overwhelm",
	Relentless = "Relentless",
	SpecBow = "Bow Mastery",
	SpecCrossbow = "Crossbow Mastery",
	SpecThrowing = "Throwing Mastery",
	SpecAxe = "Axe Mastery",
	SpecCleaver = "Cleaver Mastery",
	SpecDagger = "Dagger Mastery",
	SpecSword = "Sword Mastery",
	SpecSpear = "Spear Mastery",
	SpecPolearm = "Polearm Mastery",
	SpecHammer = "Hammer Mastery",
	SpecMace = "Mace Mastery",
	SpecFlail = "Flail Mastery",
	LegendSpecPoison = "Poison Mastery",
	LegendCascade ="Cascade strikes",
	LegendEvasion ="Evasion",
	LegendRust = "Rust",
	LegendWither = "Wither",
	LegendDeathtouch = "Death Touch",
	LegendHex = "Hex",
	LegendMiasma = "Miasma",
	LegendDarkflight = "Darkflight",
	LegendDaze ="Daze",
	LegendStunned = "Stun",
	LegendHorrify = "Horrify",
	LegendPush = "Revolt",
	LegendEntice = "Entice",
	LegendSleep = "Sleep",
	LegendFirefield = "Fire Pot",
	LegendPossessUndead = "Possess Undead",
	LegendSpecBandage = "Bandage Mastery",
	LegendHoldTheLine = "Hold the line",
	LegendCoordinatedVolleys = "Coordinated Volleys",
	LegendRaiseUndead = "Raise the Dead",
	LegendRoster = "The Apprentice",
	LegendRoster1 = "The Apprentice",
	LegendRoster2 = "The Bodyguards",
	LegendRoster3 = "The Team",
	LegendRoster4 = "The Squad",
	LegendRoster5 = "The Section",
	LegendRoster6 = "The Platoon",
	LegendRoster7 = "The Company",
	LegendForwardPush = "Push Forward",
	LegendInsects = "Insect Swarm",
	LegendChainLightning = "Chain Lightning",
	LegendComposure = "Composure",
	LegendNightvision = "Nightvision",
	LegendMasteryStaves = "Staff Mastery",
	LegendRelax = "Relax",
	LegendGruesomeFeast = "Gruesome Feast",
	LegendUberNimble = "Nudist",
	LegendMuscularity = "Muscularity",
	LegendBattleheart = "Battleheart",
	LegendTrueBeliever = "True Believer",
	LegendPoisonImmunity = "Poison Immunity",
	LegendSummonCat = "Summon Familiar",
	LegendSpawnZombieLow = "Mold Carrion",
	LegendSpawnZombieMed = "Fashion Body",
	LegendSpawnZombieHigh = "Remake Man",
	LegendSpawnSkeletonLow = "Arrange Bones",
	LegendSpawnSkeletonMed = "Align Joints",
	LegendSpawnSkeletonHigh = "Rebuild Skeleton",
	LegendExtendendAura = "Extended Aura",
	LegendChanneledPower = "Channeled Power",
	LegendReclamation = "Reclamation",
	LegendConservation = "Conservation",
	LegendEnthrall = "Enthrall",
	LegendViolentDecomposition = "Violent Decomposition",
	LegendPossession = "Possession",
	LegendSiphon = "Siphon",

	LegendValaInscriptionMastery = "Inscription Mastery",
	LegendValaInscribeWeapon = "Rune Sigils: Weapons",
	LegendValaInscribeHelmet = "Rune Sigils: Helmets",
	LegendValaInscribeArmor = "Rune Sigils: Armors",
	LegendValaInscribeShield = "Rune Sigils: Shields",
	LegendValaChantMastery = "Chanting Mastery",
	LegendValaChantDisharmony = "Disharmony (Chant)",
	LegendValaChantFury = "Fury (Chant)",
	LegendValaChantSenses = "Heightened Senses (Chant)",
	LegendValaTranceMastery = "Trance Mastery",
	LegendValaTrancePerspective = "Incorporeal Perspective (Trance)",
	LegendValaTranceMalevolent = "Malevolent Spirits (Trance)",
	LegendValaWarden = "Warden",
	LegendValaSpiritualBond = "Spiritual Bond",
	LegendValaThreads = "Threads of Fate",
	LegendValaPremonition = "Premonition",

	LegendInventorAnatomy = "Anatomical Studies",

	LegendGuideSteps = "Guide Steps",
	LegendBerserkerRage = "Berserker Rage",
	LegendAssuredConquest = "Assured Conquest",
	LegendTasteThePain = "Taste the Pain",
	LegendBecomeBerserker = "Become Berserker",
	LegendSkillfulStacking = "Skillful Stacking",
	LegendEfficientPacking = "Efficient Packing",
	LegendAmmoBinding = "Ammunition Binding",
	LegendAmmoBundles = "Ammunition Bundles",
	LegendMedPackages = "Medicine Packages",
	LegendMedIngredients = "Medicine Ingredients",
	LegendToolsDrawers = "Tools Drawers",
	LegendToolsSpares = "Spare Parts",
	LegendBarterConvincing = "Convincing Proposals",
	LegendBarterTrustworthy = "Trustworthy Demeanour",
	LegendBribe = "Bribe",
	LegendSpecialistButcherDamage = "Butchers Strikes",
	LegendSpecialistButcherSkill = "Butchers Fillet",
	LegendSpecialistHammerDamage = "Blacksmiths Heavy Hammer",
	LegendSpecialistHammerSkill = "Blacksmiths Technique",
	LegendSpecialistKnifeDamage = "Knife fighting",
	LegendSpecialistKnifeSkill = "Prisoners rush",
	LegendSpecialistLuteDamage = "Lute Solo",
	LegendSpecialistLuteSkill = "Entrancing Song",
	LegendSpecialistMilitiaDamage = "Militia training",
	LegendSpecialistMilitiaSkill = "Militia practice",
	LegendSpecialistPickaxeDamage = "Miners Strikes",
	LegendSpecialistPickaxeSkill = "Ore hunter",
	LegendSpecialistPitchforkDamage = "Stable Shoveler",
	LegendSpecialistPitchforkSkill = "Hay Bailing",
	LegendSpecialistShortbowDamage = "Small Game",
	LegendSpecialistShortbowSkill = "Poachers Arm",
	LegendSpecialistShovelDamage = "Dig deep",
	LegendSpecialistShovelSkill = "Gravesman",
	LegendSpecialistWoodaxeDamage = "Timber",
	LegendSpecialistWoodaxeSkill = "Woodsmans Cuts",
	LegendSpecialistSickleDamage = "Gatherers cuts",
	LegendSpecialistSickleSkill = "Harvest twist",
	LegendSpecialistSlingDamage = "Heavy rocks",
	LegendSpecialistSlingSkill = "Slingers spins",
	LegendBigGameHunter = "Big Game Hunter",
	LegendSecondWind = "Second Wind",
	LegendMarkTarget = "Mark Target",
	LegendFieldTriage = "Field Triage",
	LegendFieldRepairs = "Field Repairs",
	LegendDangerPay = "Danger Pay",
	LegendPreparedForAnything = "Prepare For Anything",
	LegendBrinkOfDeath = "Brink of Death",
	LegendStrictSermons = "Strict Sermons",
	LegendInfectiousRage = "InfectiousRage",
	LegendTeacher = "Teacher",
	LegendResurrectionist = "Resurrectionist",
	LegendScry = "Scry",
	LegendPiercingShot = "Piercing Shot",
	LegendLevitate = "Levitate",
	LegendTeleport = "Teleport",
	LegendSpecialistShieldSkill = "Born with a board",
	LegendSpecialistShieldPush = "Push it",
	LegendMasteryNets = "Net Mastery",
	LegendSpecialistScytheSkill = "Harvest swathes",
	LegendSpecialistScytheDamage = "Slicing arcs",
	LegendMasterySlings = "Sling Mastery",
	LegendSpecialistNinetailsDamage = "Flesh mortification",
	LegendSpecialistNinetailsSkill = "Scourging",
	LegendFavouredEnemyGhoul = "Favoured Enemy - Nachzehrers",
	LegendFavouredEnemyHexen = "Favoured Enemy - Hexen",
	LegendFavouredEnemyAlps = "Favoured Enemy - Alps",
	LegendFavouredEnemyUnhold = "Favoured Enemy - Unholds",
	LegendFavouredEnemyLindwurm = "Favoured Enemy - Lindwurms",
	LegendFavouredEnemyDirewolf = "Favoured Enemy - Direwolf",
	LegendFavouredEnemySpider = "Favoured Enemy - Spiders",
	LegendFavouredEnemySchrat = "Favoured Enemy - Schrats",
	LegendFavouredEnemyOrk = "Favoured Enemy - Orks",
	LegendFavouredEnemyGoblin = "Favoured Enemy - Goblins",
	LegendFavouredEnemyVampire = "Favoured Enemy - Necrosavants",
	LegendFavouredEnemySkeleton = "Favoured Enemy - Ancient dead",
	LegendFavouredEnemyZombie = "Favoured Enemy - Weirdergangers",
	LegendFavouredEnemyNoble = "Favoured Enemy - Noble",
	LegendFavouredEnemyBandit = "Favoured Enemy - Bandit",
	LegendFavouredEnemyBarbarian = "Favoured Enemy - Barbarian",
	LegendFavouredEnemyArcher = "Favoured Enemy - Archer",
	LegendFavouredEnemySwordmaster = "Favoured Enemy - Sword Master",
	LegendFavouredEnemyMercenary = "Favoured Enemy - Mercenary",
	LegendFavouredEnemyCaravan = "Favoured Enemy - Caravan",
	LegendSpecGreatSword = "Greatsword Mastery",
	LegendForcefulSwing = "Forceful Swing",
	LegendSpecSpearWall = "Spearwaller",
	LegendSpecSpearThrust = "Thrust Master",
	LegendBalance = "Balance",
	LegendMatchingSet = "Matching Set",
	LegendLithe = "Lithe",
	LegendHidden = "Camouflage",
	LegendBlendIn = "Blend in",
	LegendSpecStaffStun = "Staff Spins",
	LegendSpecStaffSkill = "Staff Block",
	LegendDrumsOfWar = "Drums of War"

};
gt.Const.Strings.PerkDescription <- {
	Relentless = "Don\'t slow down! At all times your Initiative is reduced only by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] of your accumulated Fatigue, instead of all of it.",
	ReturnFavor = "Unlocks the \'Return Favor\' skill which when active has a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] chance to stun any opponent missing a melee attack against this character in retaliation. Immunities and resistances against being stunned still apply.",
	PerfectFocus = "Unlocks the \'Perfect Focus\' skill which allows the use of all other skills for one round at half the normal Action Point cost (rounded down), but double the fatigue cost.",
	Rotation = "Unlocks the \'Rotation\' skill which allows two characters to switch places while ignoring Zone of Control as long as neither character is stunned, rooted or otherwise disabled.",
	Footwork = "Unlocks the \'Footwork\' skill which allows you to leave a Zone of Control without triggering free attacks by using skillful footwork.",
	Debilitate = "Unlocks the \'Debilitate\' skill which can prime your next attack to cripple a target for one turn, reducing their ability to inflict damage by [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	Furor = "Unlocks the \'Furor\' skill which allows for an unlimited number of other skill uses for a single turn until the character is completely fatigued.",
	Indomitable = "Unlocks the \'Indomitable\' skill which grants a [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] damage reduction and immunity to being stunned, knocked back, grabbed or swallowed for one turn.",
	RallyTheTroops = "Unlocks the \'Rally\' skill which can rally fleeing allies, and raise morale of all nearby allies to a steady level. The higher the Resolve of the character using the skill, the higher the chance to succeed.",
	Adrenalin = "Unlocks the \'Adrenaline\' skill which puts you first in the turn order for the next round, to have another turn before your enemies do. Feel the adrenaline rushing through your veins!",
	FirstAid = "Unlocks the \'First Aid\' skill which can stop bleeding effects, including those from serious injuries, during combat. Does not heal hitpoints.",
	Fearsome = "Make them scatter and flee! Any attack that inflicts at least 1 point of damage to hitpoints triggers a morale check for the opponent, as opposed to only if at or above 15 points of damage.",
	HeadHunter = "Go for the head! Gain [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] chance to hit the head for critical damage each time you hit the body. Bonus is reset upon hitting the head.",
	SunderingStrikes = "Effectiveness vs. Armor is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used.",
	BloodyHarvest = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] chance to hit for all area of effect attacks.",
	FastAdaption = "Adapt to your opponent\'s moves! Gain an additional stacking [color=" + this.Const.UI.Color.PositiveValue + "]+8%[/color] chance to hit with each attack that misses an opponent. Bonus is reset upon landing a hit.",
	FullForce = "Put your full weight into every blow and gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] of your current body armor as additional maximum damage.",
	Weaponmaster = "All attacks cost [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] Fatigue to use and weapon condition degrades only half as fast. Dance gracefully with your weapon and make every hit count. ",
	CoupDeGrace = "Inflict additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] damage against targets that have sustained any injury effects, like a broken arm.",
	SteelBrow = "Hits to the head no longer cause critical damage to this character, which also lowers the risk of sustaining debilitating head injuries significantly.",
	Anticipation = "When being attacked with ranged weapons, gain [color=" + this.Const.UI.Color.PositiveValue + "]1 + 10% of your base Ranged Defense[/color] as additional Ranged Defense per tile that the attacker is away.",
	HoldOut = "Keep it together! Any negative status effect with a finite duration (e.g. Bleeding, Charmed) has its duration reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] turn, to a minimum of 1 turn.",
	Dodge = "Too fast for you! Gain [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] of the character\'s current Initiative as a bonus to Melee and Ranged Defense.",
	Nimble = "Specialize in light armor! By nimbly dodging or deflecting blows, convert any hits to glancing hits. Hitpoint damage taken is reduced by up to [color=" + this.Const.UI.Color.PositiveValue + "]60%[/color], but lowered exponentially by the total penalty to Maximum Fatigue from body and head armor above 15. The lighter your armor and helmet, the more you benefit.\n\nBrawny does not affect this perk.\n\nDoes not affect damage from mental attacks or status effects, but can help to avoid receiving them.",
	BattleForged = "Specialize in heavy armor! Armor damage taken is reduced by a percentage equal to [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] of the current total armor value of both body and head armor. The heavier your armor and helmet, the more you benefit.\n\nDoes not affect damage from mental attacks or status effects, but can help to avoid receiving them.",
	DoubleStrike = "After landing a hit, the next attack does [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] damage to both hitpoints and armor. If the attack misses, the effect is wasted.",
	Vengeance = "After receiving a blow, the next attack of this character will inflict [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] damage to both hitpoints and armor. If the attack misses, the effect is wasted.",
	Duelist = "Become one with your weapon and go for the weak spots! With the offhand free, an additional [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] of any damage ignores armor. Does not work with two-handed weapons.",
	CripplingStrikes = "Cripple your enemies! Lowers the threshold to inflict injuries by [color=" + this.Const.UI.Color.NegativeValue + "]33%[/color] for both melee and ranged attacks.",
	QuickHands = "Looking for this? Swapping items in battle becomes a free action with no Action Point cost once every turn.",
	TrophyHunter = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color] permanent hitpoint for every opponent slain.",
	Bruiser = "Effectiveness vs. Armor is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for any weapon used.",
	Crusher = "Put full force in your every blow! Shield damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+50%[/color] when using the Split Shield skill.",
	CloseCombatArcher = "If you can see the white in your enemy\'s eyes, aim for it! Damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+50%[/color] when using a ranged weapon (including throwing weapons) against a target 2 or less tiles away.",
	Bullseye = "Nailed it! The penalty to hitchance when shooting at a target you have no clear line of fire to is reduced from [color=" + this.Const.UI.Color.NegativeValue + "]75%[/color] to [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] for ranged weapons.",
	Ballistics = "The range penalty to hitchance is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] per tile.",
	Berserk = "RAAARGH! Once per turn, upon killing an enemy, [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] Action Points are immediately regained. Characters can not regain more than their maximum Action Points and no more than 4 for a single attack.",
	Slaughterer = "Melee kills always are fatalities and have a [color=" + this.Const.UI.Color.NegativeValue + "]-15[/color] penalty to enemy Resolve checks. A gruesome display, enemies are more likely to suffer from hits to morale as their allies get carved up and split in two.",
	BetweenTheEyes = "The chance to hit the head for critical damage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for all attacks.",
	BattleFlow = "Once per turn, killing an opponent reduces current fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] of the base maximum fatigue (before penalties due to armor are applied).",
	DevastatingStrikes = "All damage inflicted is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+20%[/color] for any weapon used. What could stand before you now?",
	KillingFrenzy = "Go into a killing frenzy! A kill increases all damage by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] for 2 turns. Does not stack, but another kill will reset the timer.",
	ShieldBash = "The Knock Back skill now also inflicts [color=" + this.Const.UI.Color.DamageValue + "]10 - 25[/color] Damage (50% effective against armor) and [color=" + this.Const.UI.Color.DamageValue + "]10[/color] Fatigue in addition to its normal effect, and costs 10 Fatigue less to use.",
	Brawny = "The fatigue and initiative penalty from wearing armor and helmet is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color].",
	Stalwart = "Grants passive immunity against being knocked back, pulled, grabbed or swallowed. Applies to skills such as Knock Back, Hook and others that change a character\'s position. Does not grant the damage reduction of indomitable, but also doesn\'t require activation.",
	Steadfast = "Getting hit by regular attacks does not cause a loss of fatigue anymore. Attacks that specifically target fatigue are unaffected.",
	Taunt = "Unlocks the \'Taunt\' skill which makes the targeted opponent take offensive actions instead of defensive ones, and attack the taunting character over another, potentially more vulnerable one.",
	Colossus = "Bring it on! Hitpoints are increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color], which also reduces the chance to sustain debilitating injuries when being hit.",
	Deflect = "Learn to better deflect hits to the side instead of blocking them head on. Shield damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color] to a minimum of 1.",
	Evade = "A moving target is an elusive one. On getting hit with a ranged attack, there is a [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] chance to only take a gracing hit and suffer only [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] of the normal damage.",
	ShieldExpert = "Learn to better deflect hits to the side instead of blocking them head on.\n\nThe shield defense bonus is increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color]. This also applies to the additional defense bonus of the Shieldwall skill.\n\nShield damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color] to a minimum of 1.\n\nThe \'Knock Back\' skill gains [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] chance to hit.",
	NineLives = "Once per battle, upon receiving a killing blow, survive instead with a few hitpoints left. The next hit is likely to kill you for good, of course.",
	BatteringRam = "Immunity against being stunned.",
	LastStand = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+1%[/color] additional Melee and Ranged Defense for every 1% of hitpoints missing.",
	Ironside = "All damage received is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-5%[/color] for every opponent adjacent and in melee range, up to a [color=" + this.Const.UI.Color.NegativeValue + "]-30%[/color] total damage reduction.",
	BagsAndBelts = "Unlock two extra bag slots to carry all your favorite things. Items placed in bags no longer give a penalty to Maximum Fatigue, except for two-handed weapons and shields.",
	Rebound = "Fatigue regeneration is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color] per turn.",
	Feint = "If an attack misses, it costs [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color] less fatigue than normal.",
	Student = "Everything can be learned if you put your mind to it. Gain additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] experience from battle. At the eleventh character level, you gain an additional perk point and this perk becomes inert.",
	Gifted = "Mercenary life comes easy when you\'re naturally gifted. Instantly gain a levelup to increase this character\'s attributes with maximum rolls, but without talents.",
	Lookout = "Learn to find your enemies before they find you. Vision is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	Zweihander = "Fatigue costs for all two-handed weapon skills are reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-20%[/color].",
	Pathfinder = "Learn to move on difficult terrain. Action Point costs for movement on all terrain is reduced by [color=" + this.Const.UI.Color.NegativeValue + "]-1[/color] to a minimum of 2 Action Points per tile, and Fatigue cost is reduced to half. Changing height levels also has no additional Action Point cost anymore.",
	FortifiedMind = "An iron will is not swayed from the true path easily. Resolve is increased by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color].",
	Captain = "Use a sergeant on the battlefield as an extension of your leadership and to keep everyone in line. Allies at a range of 5 tiles or less will get [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] of this character\'s Resolve as a bonus added to their own, up to a maximum of this character\'s Resolve.\n\nDoes not stack; the sergeant with the highest Resolve will apply the bonus.",
	BoondockBlade = "When in a hiding place, such as high grass, gain a bonus of [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] to Melee Skill, Ranged Skill, and Melee and Ranged Defense.",
	ArtfulDodger = "Zone of Control is ignored when moving away from enemy combatants in melee.",
	InspiringPresence = "A great leader of men inspires his followers to overcome their limits. Allies start every battle at confident morale unless prohibited by character traits.",
	Inspire = "Unlocks the \'Inspire\' skill which can push allies to go beyond their limits, granting them additional Action Points.",
	Underdog = "I\'m used to it. The defense malus due to being surrounded by opponents is reduces by 5. If an attacker has the Backstabber perk, the effect of that perk is negated, and the normal defense malus due to being surrounded is applied instead.",
	Sprint = "Unlocks the \'Sprint\' skill which allows for sprinting over short distances in straight lines instantly.",
	Recover = "Unlocks the \'Recover\' skill which allows for resting a turn in order to reduce accumulated Fatigue by [color=" + this.Const.UI.Color.NegativeValue + "]50%[/color].",
	FirstMove = "Always act first in the very first round of combat, before any of your opponents do.",
	Backstabber = "Honor doesn\'t win you fights, stabbing the enemy where it hurts does. The bonus to hitchance in melee is doubled to [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] for each ally surrounding and distracting your target.",
	LoneWolf = "I work best alone. With no ally within 3 tiles of distance, gain a [color=" + this.Const.UI.Color.PositiveValue + "]15%[/color] bonus to Melee Skill, Ranged Skill, Melee Defense, Ranged Defense, and Resolve.",
	ReachAdvantage = "Learn to use the superior reach of large weapons to keep the enemy from getting close enough to land a good hit.\n\nEach hit with a two-handed melee weapon adds a stack of Reach Advantage that increases your Melee Defense by [color=" + this.Const.UI.Color.PositiveValue + "]+5[/color], up to a maximum of 5 stacks, until this character\'s next turn. A single attack hitting multiple targets can add several stacks at once.\n\nIf you put away your weapon, you lose all stacks.",
	Overwhelm = "Learn to take advantage of your high Initiative and prevent the enemy from attacking effectively by overwhelming them with your attacks!\n\nWith every attack, hit or miss, against an opponent that acts after you in the current round, inflict the \'Overwhelmed\' status effect which lowers both Melee Skill and Ranged Skill by [color=" + this.Const.UI.Color.NegativeValue + "]10%[/color] for one turn.\n\nThe effect stacks with each attack, and can be applied to multiple targets at once with a single attack.",
	SpecBow = "Master the art of archery and pelting your opponents with arrows from afar. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nView range and maximum firing range with bows is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	SpecCrossbow = "Master crossbows and learn where to aim best. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nAn additional [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] of damage inflicted with crossbows ignores armor.",
	SpecThrowing = "Master throwing weapons to wound or kill the enemy before they even get close. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nDamage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]40%[/color] when attacking at 2 tiles of distance.\n\nDamage is increased by [color=" + this.Const.UI.Color.PositiveValue + "]20%[/color] when attacking at 3 tiles of distance.",
	SpecAxe = "Master combat with axes and destroying shields. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nSplit Shield damage to shields is increased by [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] when used with axes.\n\nRound Swing gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.\n\nThe Longaxe no longer has a penalty for attacking targets directly adjacent.",
	SpecCleaver = "Master cleavers to inflict gruesome wounds. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nBleeding damage inflicted by cleavers and whips is doubled to [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] and [color=" + this.Const.UI.Color.PositiveValue + "]20[/color] per turn, respectively.\n\nDisarm no longer has a penalty to hit.",
	SpecDagger = "Master swift and deadly daggers. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nStab and Puncture have a reduced Action Point cost to allow for an additional attack each turn.",
	SpecSword = "Master the art of swordfighting and using your opponent\'s mistakes to your advantage. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nRiposte no longer has a penalty to hitchance.\n\n Slash, Gash and Lunge gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.",
	SpecSpear = "Master fighting with spears and keeping the enemy at bay. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nSpearwall is no longer disabled once an opponent manages to overcome it. Instead, Spearwall continues to give free attacks on any further opponent attempting to enter the Zone of Control.\n\nThe Spetum and Warfork no longer have a penalty for attacking targets directly adjacent.",
	SpecPolearm = "Master polearms and keeping the enemy at bay. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nPolearm skills have their Action Point cost reduced to [color=" + this.Const.UI.Color.NegativeValue + "]5[/color], and no longer have a penalty for attacking targets directly adjacent.",
	SpecHammer = "Master hammers and fighting against heavily armored opponents. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nDestroy Armor and Demolish Armor inflict [color=" + this.Const.UI.Color.PositiveValue + "]33%[/color] more damage against armor.\n\nShatter gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.\n\nThe Polehammer no longer has a penalty for attacking targets directly adjacent.",
	SpecMace = "Master maces to beat your opponents into submission, armored or not. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nKnock Out and Strike Down have a [color=" + this.Const.UI.Color.PositiveValue + "]100%[/color] chance to stun the target if not immune.",
	SpecFlail = "Master flails and circumvent your opponent\'s shield. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nLash and Hail ignore the defense bonus of shields.\n\nThresh gains [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.",
	LegendSpecPoison = "Master poison, giving you the ability to keep your weapons covered in poison at all times",
	LegendCascade = "Let loose a cascade of three striking heads on your opponent. Will strike over or around shield cover.",
	LegendEvasion = "Enables the character for one turn to move swiftly and safely through any Zone of Control without incurring any free attacks.",
	LegendRust = "Deform, rip and otherwise render the target\'s armor unusable with great effect. Although the impact will be felt through the thickest of armor, it won\'t inflict the most injury to the wearer.",
	LegendWither = "Debilitate a target for one turn, reducing their ability to inflict damage by [color=" + this.Const.UI.Color.NegativeValue + "]-50%[/color].",
	LegendDeathtouch = "Your fingers turn ghostly and pass through steel and flesh, tearing at the soul of your victim",
	LegendHex = "You tie your soul to your enemy, your pain becomes their pain",
	LegendMiasma = "Release a cloud of noxious gasses that are harmful to any living being",
	LegendDarkflight = "Disapperate from your current location and reappear on the other side of the battlefield up to 6 tiles away",
	LegendDaze = "Assault the senses of your target with a flurry of colorful sparks, whirs, and pops. Such an astonishing display is sure to leave anyone too bewildered to fight effectively. Does no damage",
	LegendStunned = "Unleash a brilliant flash of white light aimed directly at the eyes of your target in an attempt to blind and incapacitate.",
	LegendHorrify = "Blare out a piercing, unworldly sound that is more than likely to distress anyone unfortunate enough to hear it.",
	LegendPush = "Concoct a mixture of smells so fetid and noxious, you force your target to retreat just so they can breathe.",
	LegendEntice = "With a trick of the light, captivate your target in such a way that they can\'t help but approach you."
	LegendSleep  = "Enshroud the area with thick smoke that draws the vigor out of your foes. Those that breathe in too much are forced into a light sleep.",
	LegendFirefield = "throw a noxious concoction that sets the ground alight. Requires a staff",
	LegendPossessUndead = "Allows you to boost the attacks of an undead minion",
	LegendSprint = "For the remainder of this turn, the Action Point cost for movement is reduced by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] for each tile, but the Fatigue cost is doubled.",
	LegendRoster = "Increase roster size",
	LegendSpecBandage = "Master the art of bandaging mid battle using any cloth available, this character no longer requires a bandage item to bandage allies, and can bandage while in a zone of control",
	LegendHoldTheLine = "Direct your troops to stand their ground, granting [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] melee defence to all allies within [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] tiles for one turn",
	LegendCoordinatedVolleys = "Direct your troops to time their shots, granting [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] ranged attack to all allies within [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] tiles for one turn",
	LegendRaiseUndead = "Raise the dead, and turn them into your own personal army",
	LegendRoster1 = "Direct your attention to guiding an apprentice into the mercenary world, increasing the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color]",
	LegendRoster2 = "Spend time training bodyguards to work together, increasing the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]2[/color]",
	LegendRoster3 = "Set up team planning, with task lists and prioritisation. Increases the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]3[/color]",
	LegendRoster4 = "Create a squad regime, with weekly schedules and drills. Increases the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]4[/color]",
	LegendRoster5 = "Oversee the section\'s financial administration processes, managing pay disputes, disbursements, withholdings and loans.  Increases the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]5[/color]",
	LegendRoster6 = "Manage the company logistics. Supply rationing, camp structure and waste disposal. Increases the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]6[/color]",
	LegendRoster7 = "Implement platoon organisation techniques. Balancing interteam dynamics, clarifying role responsibilities, creating conflict resolution processes and creating strategic plans.  Increases the company roster size by [color=" + this.Const.UI.Color.PositiveValue + "]7[/color]",
	LegendInsects = "Unleash a horde of insects on your enemy, halving their melee skill, melee defense, ranged skill, ranged defense and initiative",
	LegendForwardPush = "Direct your troops to attack at once, granting [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] melee skill to all allies within [color=" + this.Const.UI.Color.PositiveValue + "]4[/color] tiles for one turn",
	LegendChainLightning = "Unleash an arcing barrage that strikes an opponent and sending sparks on to another 3 enemies, dealing additional damage and ignoring armor. Requires a staff",
	LegendComposure = "Train to keep your cool, under even the most challenging circumstances. Grants immunity to stun",
	LegendNightvision = "Use your superior vision and training to spot targets in the gloom, and grant that vision to your allies",
	LegendMasteryStaves = "Master the art of fighting with staves. Use less action points and fatigue when using Missile, Revolt, Entice, Chain Lightning and Firefield. Missile gains 1 range",
	LegendGruesomeFeast = "Taste of the forbidden flesh. Devour a recently departed corpse to gain strength and restore your own health by [color=" + this.Const.UI.Color.PositiveValue + "]50[/color] ",
	LegendRelax = "Sooth an ally, halving their fatigue",
	LegendUberNimble = "Gain another stack of nimble when not wearing armour or helmet, real berserkers don\'t need pants",
	LegendMuscularity = "Put your full weight into every blow and gain [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] of your current hitpoints as additional maximum damage.",
	LegendBattleheart = "Wade into the thick of battle, dodging blades from behind and above, aware of all around you at the heart of the battle. Being surrounded no longer effects this character\'s defences at all. upgraded version of underdog, immune to Backstabber",
	LegendTrueBeliever = "Lesser men may cower and flee, but you are unassuageable in your commitment. Allies fleeing no longer lowers this character\'s morale",
	LegendPoisonImmunity = "With a well developed immune system and incredible fitness, a warrior\'s system can shrug off even powerful toxins. This character becomes immune to all poisons.",
	LegendSummonCat = "Summon feline familiar to your aide. Don't worry, this particular cat has nine times a million lives.",
	LegendSpawnZombieLow = "Raise a half-formed thrall from a pile of mismatched dead flesh. Though lacking in strength or bodily integrity, it shall obey. Requires a small flesh sacrifice to perform the ritual.",
	LegendSpawnZombieMed = "Organize the remains before you raise it so that your creation is better suited to the work it is given. Sturdier in both form and function. Requires a minor flesh sacrifice to perform the ritual.",
	LegendSpawnZombieHigh = "Stitch the body together with such precision so that, once raised, it could pass as alive. A magnum opus of flesh, unsurpassed in power. Requires a moderate flesh sacrifice to perform the ritual.",
	LegendSpawnSkeletonLow = "Raise a ramshackle thrall from some bones only barely ordered. Though lacking in strength or bodily integrity, it shall obey. Requires a small flesh sacrifice to perform the ritual.",
	LegendSpawnSkeletonMed = "Place the bones where they belong before you raise them so that it’s less liable to fall apart. Sturdier in both form and function. Requires a minor flesh sacrifice to perform the ritual.",
	LegendSpawnSkeletonHigh = "Painstakingly reorganize each bone such that, once raised, no tarsus is out of place. A magnum opus of bone, unsurpassed in power. Requires a moderate flesh sacrifice to perform the ritual.",
	LegendExtendendAura = "Yield to the dark power, let it ooze from your pores. With the fell energy now unrestrained, you can further project your art of rousing the dead. Increases range of all skills that raise dead by one tile.",
	LegendChanneledPower = "Learn to better focus your art so it is less draining on your body. All skills that raise dead build up 30% less Fatigue.",
	LegendReclamation = "Weave a bit of your magic through the waste of a corpse so more means may be salvaged. Increases how frequently you gain Human Carrion and Human Bones as loot.",
	LegendConservation = "Conduct profane rituals meant to stave off the passage of time, further preserving the means of your craft. Reduces the cost of maintaining Human Carrion and Human Bones by 50% medicine per day.",
	LegendEnthrall = "Pull at the strings of a single creation, compelling them to linger among you as an obedient guardian. Enthralled dead act defensively and attempt to protect you from threats.",
	LegendViolentDecomposition = "Corrupt the force sustaining one of your thralls, causing them to detonate destructively after the corruption has time to build. Affected dead explode at the end of their turn next round, dealing damage in a 1 tile radius. The less HP they have, the more damage the explosion inflicts. If they are killed before they explode, the effect no longer triggers.",
	LegendPossession = "Enter the mind of a thrall and lend your power for one turn, increasing thralls combat prowess.",
	LegendSiphon = "Draw from the lifeforce of your victim and transfer up to 30% of their health to yourself. You may not drain more health than you are missing nor drain a victim to their death. Effectiveness drops off 5% for each tile away.",

	LegendValaInscriptionMastery = "The Vala becomes a master at inscribing the intricate and subtle signs, allowing her to create the rune sigils at faster rate.",
	LegendValaInscribeWeapon = "Allows the Vala to inscribe rocks with weapon specific rune sigils while encamped.\n\nPossibilities: accuracy, bleeding, feeding, poison, power.",
	LegendValaInscribeHelmet = "Allows the Vala to inscribe rocks with helmet specific rune sigils while encamped.\n\nPossibilities: bravery, clarity, luck.",
	LegendValaInscribeArmor = "Allows the Vala to inscribe rocks with armor specific rune sigils while encamped.\n\nPossibilities: endurance, resilience, safety.",
	LegendValaInscribeShield = "Allows the Vala to inscribe rocks with shield specific rune sigils while encamped.\n\nPossibilities: defense, radiance.",
	LegendValaChantMastery = "Chants build up 25% less Fatigue and have greater potency.",
	LegendValaChantDisharmony = "A very disagreeable and cacophonous chant that makes it almost impossible for the Vala\'s enemies to focus and concentrate properly.\n\nEnemies adjacent to the Vala are unable to enforce Zones of Control, making it easy to slip past them.",
	LegendValaChantFury = "A chant that really gets the blood boiling, making your allies eager to fight.\n\nAllies within 3 tiles of the Vala, including the Vala herself, receive a bonus to their damage output and a chance to retaliate against attackers that hit them in melee range.",
	LegendValaChantSenses = "An intriguing chant that stimulates the senses, increasing all allies\' awareness.\n\nAllies within 3 tiles of the Vala, including the Vala herself, receive a bonus to their melee and ranged defenses.",
	LegendValaTranceMastery = "Entering trances builds up 25% less Fatigue. Gain a 50% chance to not drop out of trance when receiving damage. Successful trances are more likely to occur.",
	LegendValaTrancePerspective = "Incorporeal Perspective.",
	LegendValaTranceMalevolent = "The spirit world is home to many malevolent beings, and the Vala knows how to contact them. Once her access to their realm has been established, she calls upon these ill-willed spirits in hopes of receiving their help.\n\nIf she\'s successful, these spirits will harass, torment and weaken her foes. They may also spread out to affect additional entities.",
	LegendValaWarden = "Each individual has a warden spirit that follows their soul from birth to death. The Vala, being spiritually attuned, has a remarkable connection to and relation with her Warden which allows it to manifest itself in a semi-physical form and help her out during battle.\n\nAutomatically summons the Warden at the start of a fight. It can be beaten, but it never dies.",
	LegendValaSpiritualBond = "The bond between the Vala and her Warden has grown strong with the passing of time. A percentage of the Vala\'s incoming health damage is dealt to the Warden instead, up to a maximum of 50%. The Warden also gain a scaling damage bonus.\n\nThis perk does nothing unless the Vala has the Warden perk.",
	LegendValaThreads = "As the Vala swings and weaves her staff she spins and twines the threads of fate of those she hits with it.\n\nThe Vala needs her staff equipped for this perk to work, and then each attack has a chance to apply a stacking debuff. Each stack lowers maximum hitpoints and increases amount of damage taken.",
	LegendValaPremonition = "As if being warned by some higher being, the Vala occasionally gets glimpses of the immediate future and any dangers it may hold, letting her prepare herself accordingly.\n\nHelps the Vala avoid incoming damage. Her understanding of these visions grows stronger as she becomes more experienced.",

	LegendInventorAnatomy = "Anatomical Studies",

	LegendGuideSteps = "Gives you the Guide Steps skill, that lets you grant Pathfinder to all your allies",
	LegendBerserkerRage = "Gain rage stacks over the course of a battle. Each stack increases Damage by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color], initiative by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color], resolve by [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] and reduces damage received by [color=" + this.Const.UI.Color.PositiveValue + "]2%[/color]. Gain [color=" + this.Const.UI.Color.PositiveValue + "]1[/color] stack each time you hit, and [color=" + this.Const.UI.Color.PositiveValue + "]3[/color] stacks each time you kill. ",
	LegendAssuredConquest = "[color=" + this.Const.UI.Color.PositiveValue + "]10%[/color] melee skill, melee defense and ranged defense when at confident morale",
	LegendTasteThePain = "Whenever getting hurt would normally trigger a morale check, instead gain [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] morale",
	LegendBecomeBerserker = "This character background changes into a berserker, losing all current perks",
	LegendSkillfulStacking = "Balancing things is an art, by creating neat stacks and tying them down well you can carry more gear. Grants 10 additional stash spaces.",
	LegendEfficientPacking = "Arranging gear in just the right way, you're able to squeeze more things into the same space. Grants 5 additional stash spaces.",
	LegendAmmoBinding = "Expertise in making ammunition lets you strip it down to pack the parts for storage. Increases maximum ammunition storage by 10.",
	LegendAmmoBundles = "Using blankets and ropes to group large bundles of ammunition together you are able to carry far more. Increases maximum ammunition storage by 20.",
	LegendMedPackages = "Your knowledge of medicines lets you repack them into more efficient packages. Increases maximum medicine storage by 10.",
	LegendMedIngredients = "Not all of a plant is required for healing, your knowledge of the active ingredients lets you throw away excess leaves and roots. Increases maximum medicine storage by 20. ",
	LegendToolsDrawers = "Organising your tools into labeled compartments lets you carry more. Increases maximum tool storage by 10",
	LegendToolsSpares = "Your experience with repairs has taught you to save your scraps and left over parts. These spares take up little space but are often just what you need for field repairs. Increases maximum tool storage by [color=" + this.Const.UI.Color.PositiveValue + "]20[/color].",
	LegendBarterConvincing = "This characters skill with words makes their trade proposals more acceptable. Grants +2.5% barter",
	LegendBarterTrustworthy = "This characters body language makes people believe them, leading to more favourable trade agreements. Grants +5% barter",
	LegendBribe = "Throw coins at your enemies to bribe them away from battle, only works on humans.",
	LegendSpecialistButcherDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]5-15[/color] damage while using a Butchers Cleaver. Does not apply to other cleavers.",
	LegendSpecialistButcherSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill while using a Butcher\'s Cleaver. Does not apply to other cleavers.",
	LegendSpecialistHammerDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]5-15[/color] damage while using a Blacksmith\'s Hammer. Does not apply to other hammers.",
	LegendSpecialistHammerSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill and +50% armor damage while using a Blacksmiths Hammer. Does not apply to other hammers.",
	LegendSpecialistKnifeDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]5-15[/color] damage while using a Knife. Does not apply to other daggers.",
	LegendSpecialistKnifeSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill and +50% armor penetration while using a knife. Does not apply to other daggers.",
	LegendSpecialistLuteDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-20[/color] damage while using a lute.",
	LegendSpecialistLuteSkill = "Gain the \'Entice\' skill while using a lute",
	LegendSpecialistMilitiaDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]5-10[/color] damage while using a militia spear. Does not apply to other spears",
	LegendSpecialistMilitiaSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill while using a militia spear. Does not apply to other spears",
	LegendSpecialistPickaxeDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]5-10[/color] damage while using a pickaxe. Does not apply to hammers",
	LegendSpecialistPickaxeSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill while using a pickaxe. Does not apply to hammers",
	LegendSpecialistPitchforkDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-20[/color] damage while using a pitchfork. Does not apply to other pikes.",
	LegendSpecialistPitchforkSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skills and 25% armor damage while using a pitchfork. Does not apply to other pikes.",
	LegendSpecialistShortbowDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-20[/color] damage while using a shortbow. Does not apply to other bows.",
	LegendSpecialistShortbowSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] ranged skill and 25% armor damage while using a shortbow. Does not apply to other bows. ",
	LegendSpecialistShovelDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-20[/color] damage while using a shovel. Does not apply to maces.",
	LegendSpecialistShovelSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill and gain the \'Knock Out\' skill while using a shovel.",
	LegendSpecialistWoodaxeDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-20[/color] damage while using a woodaxe. Does not apply to other axes.",
	LegendSpecialistWoodaxeSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill while using a woodaxe. Does not apply to other axes",
	LegendSpecialistSickleDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15-30[/color] damage while using a sickle. Does not apply to swords.",
	LegendSpecialistSickleSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]15[/color] melee skill and [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] armor piercing while using a sickle. ",
	LegendSpecialistSlingDamage = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10-30[/color] damage while using a sling.",
	LegendSpecialistSlingSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]+25%[/color] armor damage while using a sling.",
	LegendBigGameHunter = "When targeting an enemy with more health than you, gain damage equal to their current hitpoints divided by your current hitpoints",
	LegendSecondWind = "When dropping below 30hp, regain half of your fatigue",
	LegendMarkTarget = "Mark a target, reducing their ranged defense by [color=" + this.Const.UI.Color.PositiveValue + "]20[/color]",
	LegendFieldTriage = "Spend medicine to heal a unit on the battlefield",
	LegendFieldRepairs = "Spend armor parts to repair armor on the battlefield",
	LegendDangerPay = "Spend 10 times a units daily wage to set them at confident morale",
	LegendPreparedForAnything = "Instruct your mercenaries how to secret additional supplies about their person during battle, granting the \'Bags and Belts\' perk to anyone you fight with.",
	LegendBrinkOfDeath = "Use your knowledge of undeath to bring your mercenaries back from the dead",
	LegendStrictSermons = "Endlessly repeating the lessons of the old gods to your mercenaries will imbue them with faith in the heat of battle. Grants the \'Fortified Mind\' perk to anyone you fight with.",
	LegendInfectiousRage = "The frenzy of the berserker rage is aided with clouds of herbs and ritual dances. These can be spread to your allies granting the \'Berserk\' perk to anyone you fight with.",
	LegendTeacher = "The technqiues you have mastered are inspirational and inspire curiosity in those who behold, granting the \'Student\' perk to anyone you fight with.",
	LegendResurrectionist = "This character\'s experience with corpses gives an additional [color=" + this.Const.UI.Color.PositiveValue + "]5%[/color] chance to retrieve each human body from the battlefied.",
	LegendScry = "Use your extrodinary senses to notice things no one else can. Reveals everything within 12 tiles",
	LegendPiercingShot = "Launch a shot so powerful it can hit two targets in a straight line",
	LegendLevitate = "Levitate a person above the ground, making movement across any terrain cost 1 AP and 2 Fatigue per tile",
	LegendTeleport = "Step through the world, disapearing from one place and reappearing in another place immediately.",
	LegendSpecialistShieldSkill = "Gain [color=" + this.Const.UI.Color.PositiveValue + "]10[/color] Melee Defense while using a shield",
	LegendSpecialistShieldPush = "The skill \'Knock Back\' costs [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] less fatigue and action points",
	LegendMasteryNets = "Use advanced net throwing techniques to reduce the fatigue cost by [color=" + this.Const.UI.Color.PositiveValue + "]25%[/color] and reduce AP cost to [color=" + this.Const.UI.Color.PositiveValue + "]3[/color]",
	LegendSpecialistScytheSkill = "Practicing with the unweildy scythe has taught you how to twist your torso to produce repeatable smooth strokes. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+15[/color] melee skill while weilding a scythe",
	LegendSpecialistScytheDamage = "There is a trick to sharpening the blades of scythes, and shifting the position of the handles turns it from a farming tool into a weapon. Mastering these tricks increases the damage output of scythes by [color=" + this.Const.UI.Color.PositiveValue + "]+10-15[/color]"
	LegendMasterySlings = "Master the difficult angles and timings of slinging rocks from afar. \n\n Accuracy with slings is incerased by [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] and maximum firing range with slings is increased by [color=" + this.Const.UI.Color.PositiveValue + "]+1[/color].",
	LegendSpecialistNinetailsDamage = "Turn the tips of the cattail to inflict maximum injury, increases damage by [color=" + this.Const.UI.Color.PositiveValue + "]+5-10[/color] while using the cat o nine tails, does not apply to other whips.",
	LegendSpecialistNinetailsSkill = "Practice in the arts of punishment grants greater accuracy with the unweildy weapon, granting [color=" + this.Const.UI.Color.PositiveValue + "]+15[/color] melee skill while using the cat o nine tails, does not apply to other whips.",
	LegendFavouredEnemyGhoul = "Studying these monstrosities has given you insights into the strengths and weaknesses of the palid necrophilic flesh devourers. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Nachzehrer you kill.",
	LegendFavouredEnemyHexen = "Understanding the techniques of the malevolent crones gives you protection against their coven.  Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Hexe you kill",
	LegendFavouredEnemyAlps = "Preparing for the nightmare creepers gives you techniques against their haggard curses.  Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Alps you kill. Taking this perk unlocks an extremely difficult legendary contract to hunt a fire breathing nightmare demon.",
	LegendFavouredEnemyUnhold = "These gigantic ravenous creatures are dangerous but stupid, that can be used to your advantage. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Unholds you kill. Taking this perk unlocks an extremely difficult legendary contract to hunt a stone skinned Mountain Unhold.",
	LegendFavouredEnemyLindwurm = "Understanding the morphology of these noxious serpents opens up weak spots in their scales. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Lindwurm you kill. Taking this perk unlocks an extremely difficult legendary contract to hunt a burrowing Stollwurm",
	LegendFavouredEnemyDirewolf = "The vicious jaws of a direwolf can tear limbs assunder. In the heat of their blood soaked frenzy, they leave themselves open for counter attack. Understanding these weaknesses grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more wolfs you kill.",
	LegendFavouredEnemySpider = "These skittering deadly bugs can be bested by studying the behaviour of arachnids. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more webnechts you kill. Taking this perk unlocks an legendary contract to hunt extremely poisonous Redback Webnecht",
	LegendFavouredEnemySchrat = "The strong branches of a living tree are deadly foes, but trees can be felled with the right knowledge. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Schrats you kill. Taking this perk unlocks an legendary contract to hunt en endlessly multiplying Heartwood Schrat",
	LegendFavouredEnemyOrk = "These marauding brutes are a force to be reckoned with, though their fighting style lacks finesse and can be countered with the right techniques. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Orcs you kill.",
	LegendFavouredEnemyGoblin = "Forces may be gathering to take over the world, but ask someone else, i have no interest in anything but goblins. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Goblins you kill.",
	LegendFavouredEnemyVampire = "The terrifying abilities of the Necrosavants are developed over time beyond memory. Their techniques are honed to perfection, but that also makes them predictable. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Necrosavants you kill.",
	LegendFavouredEnemySkeleton = "The legions from the ancient empire still harass this world, yet their connection to the world of the living can be severed. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Skeletons you kill.",
	LegendFavouredEnemyZombie = "Shambling corpses come wave on wave, rising sleepless from their graves. They lose something crucial in death, and that can be exploited. Grants bonus to melee skill, ranged skill and maximum damage. Bonus increases the more Wiederganger you kill."
	LegendFavouredEnemyNoble = "Soliders in glittering armor and colourful pennants, their pride shall be their undoing. No gods, no masters. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a noble soldier.",
	LegendFavouredEnemyBandit = "Villainous scum, hiding in the dark and stealing from good folk. The bandits must be purged to restore order in the world. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a bandit.",
	LegendFavouredEnemyBarbarian = "Savages, naught but savages. Civilisation must be brought to those godless brutes. They may be strong, but they lack skill. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a barbarian",
	LegendFavouredEnemyArcher = "Some may claim to be the greatest shot in the land, but none have outshot you yet. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on an archer",
	LegendFavouredEnemySwordmaster = "The path to martial prowess is beset by the fake and the weak. Only one can be the greatest swordsman. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a sword master",
	LegendFavouredEnemyMercenary = "Mercenaries are the worst, no cause, no principles, no honour. They seek only coin, so they shall find only death. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a mercenary",
	LegendFavouredEnemyCaravan = "Civilians are weak and powerless. Their pitiful lives are pathetic, they should be grateful to behold true might in their dying moments. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+10[/color] Melee skill and ranged skill and [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] maximum damage for any attack on a civilian",
	LegendSpecGreatSword = "Master the art of fighting with a large unwieldy sword. Skills build up [color=" + this.Const.UI.Color.NegativeValue + "]25%[/color] less Fatigue.\n\nSplit, Swing, Overhead Strike and Great Slash gain [color=" + this.Const.UI.Color.PositiveValue + "]+5%[/color] chance to hit.",
	LegendForcefulSwing = "Use the power of your hips and core to imbue more force into your swings. AOE skills do [color=" + this.Const.UI.Color.PositiveValue + "]+10%[/color] damage. "
	LegendSpecSpearWall = "Endless training in holding the line in a spear wall has made it a second nature. Spearwall costs[color=" + this.Const.UI.Color.NegativeValue + "]-25%[/color] less fatigue. Stacks with spear mastery ",
	LegendSpecSpearThrust = "Poking things where they don\'t belong is just a natural inclination for some. Thrust does [color=" + this.Const.UI.Color.PositiveValue + "]+15%[/color] damage."
	LegendBalance = "Some favour heavy armor, others prefer lightweight. A few strive to find the perfect balance protection and movement. Grants up to [color=" + this.Const.UI.Color.PositiveValue + "]+50[/color] bonuse melee and ranged defense if your maximum armor value matches your current initiative. The value decreases for every point of difference between the two, to a minimum of 5",
	LegendMatchingSet = "Proper distribution of weight is crucial for maintaining mobility. Grants up to  [color=" + this.Const.UI.Color.PositiveValue + "]5[/color] fatigue per round if your helmet and armor values match. Decreases by 1 for every 10 points difference.",
	LegendLithe = "Not as nimble as some, but more lithe than most. Like nimble, but with the 15 fatigue floor raised to  [color=" + this.Const.UI.Color.PositiveValue + "]30[/color], and the bonus halved"
	LegendHidden = "Master the art of concelement. Blend in with your surroundings and remain hidden from the enemy until your next attack.",
	LegendBlendIn = "Hold yourself in a way that makes you seem more trouble than its worth, lean into trees, place objects between you and an enemy, and hide behind allies. Makes enemies [color=" + this.Const.UI.Color.PositiveValue + "]50%[/color] less likely to attack you instead of an ally.",
	LegendSpecStaffStun = "Master the movements required to spin your staff in a great flourish that lands with additional force. Any strike with a staff that would normally daze, also stuns",
	LegendSpecStaffSkill = "Twist and thrust with your staff to deflect blows and intercept strikes. Grants [color=" + this.Const.UI.Color.PositiveValue + "]+20[/color] melee defense",
	LegendDrumsOfWar = "Learn powerful rythms that drive your allies on. Unlocks the Drums of War skill that restores 10 fatigue to every ally on the field."
};
gt.Const.Strings.Tooltip <- {
	World = {
		Hint_FocusParty = "Click to focus party",
		Hint_FocusLocation = "Click to focus location"
	},
	Tactical = {
		Hint_FocusCharacter = "Click to focus character",
		Hint_CannotChangeItemInCombat = "Can not be changed in combat",
		Hint_OnlyActiveCharacterCanChangeItemsInCombat = "Only the character whose turn it is right now can change items"
	}
};

