local gt = this.getroottable();
gt.Const.TipOfTheDay <- [
	"Peddlers trade bonuses stack, trade runs are possible",
	"The Warlock uses medicine to keep his minions ready to summon",
	"Alt click on friendly caravans to attack them",
	"Shields take minor damage each time they are used to deflect an attack.",
	"Shrubbery can hide characters from being detected from afar.",
	"A character with a height level advantage over their opponent is harder to hit.",
	"Characters can see farther, the higher they are positioned.",
	"Hiring different backgrounds effects your heal, repair, tradem, food and movement",
	"Female professions have more fatigue but less health than their male counterparts",
	"Your stash size is determined by the people you hire",
	"Apprentices, blacksmiths and ironongers can help repair your equipment quickly",
	"Magic damage is based on your initiative",
	"You don\'t have to be a hero, you\'re running a business.",
	"Valas are mystic women capable of inscribing powerful runes on your gear.",
	"You can save your men in multiple formations, to prepare for different fights",
	"A missed ranged attack can hit nearby characters, especially if they are in the direct line of fire.",
	"Slingstaffs have great armour penetration but poor accuracy",
	"Bows perform better against unarmored targets.",
	"Daggers can be used to attack weak spots in armor and deal damage directly to hitpoints.",
	"Melee attack damage is based on your hitpoints and initiative",
	"Consider forming a shieldwall when overwhelmed.",
	"Conserve your stamina when in prolonged engagements.",
	"Success in Battle Brothers is also about picking the right fights.",
	"Undead are unaffected by fatigue and morale.",
	"Crossbows require less skill to fire accurately than bows, but are slower to use.",
	"Hunters and poachers will help you move through forests quicker",
	"Some difficult terrain, like swamp, gives combat penalties.",
	"You can change camera height levels using the + and - keys.",
	"Miners help you move quickly through mountains, a few miners in your squad lets you quick march through hills",
	"Try to save some crowns for when things turn sour.",
	"Longswords and Greatswords can hit multiple targets with one strike.",
	"You can zoom in and out using the mouse wheel or Page Up and Page Down keys.",
	"Spears are good defensive weapons due to their Spearwall ability.",
	"Expect to lose some men.",
	"Losing is fun.",
	"The higher their level, the more your men will demand in wages.",
	"Selling in rich and big cities will net you the most crowns for your goods.",
	"Use trading to supplement your income.",
	"Learn the \'Rotation\' or \'Footwork\' perks for additional mobility in battle.",
	"View range is decreased at night, both in combat and on the worldmap.",
	"Skeletons are highly resistant to ranged attacks.",
	"Heavy armor offers great protection, but also slows down the wearer and makes him tire more quickly.",
	"Heavy helmets can be hard to breathe in and limit the field of vision.",
	"Warhammers and Military Picks can make short work of heavy armor.",
	"The Billhook, Pike and Longaxe can attack over 2 tiles, unlike most other melee weapons.",
	"Flails ignore the defense bonus of shields.",
	"Different types of enemies require different tactics to beat reliably.",
	"Every enemy in the game can be beat reliably with the right approach.",
	"A human is no match for an adult orc physically.",
	"Orcs rely on raw power and physical prowess.",
	"A goblin is no match for an adult human physically, so they rely on wit and dirty tricks.",
	"Orc Berserkers gain rage and get tougher to take down, the more blood they have drawn.",
	"Geists are lost between the physical world and the world beyond, constantly shifting between the two.",
	"Geists test the resolve of your men - the lower, the more likely they are to panic and flee.",
	"Two-handed axes can hit both head and body with a single hit.",
	"Two-handed axes can hit up to 6 targets with a single round swing.",
	"Roads are the fastest way to travel over land, but not always the safest.",
	"Forests can hide many dangers within.",
	"Always keep a good stock of provisions - lest your men starve and desert you!",
	"Wiedergangers are the dead walking again.",
	"Difficult terrain, such as mountains and swamp, has your men use more supplies on the worldmap.",
	"If you can not win, retreat to fight another day.",
	"Try to reach the very edges of the map before retreating, or you\'ll risk your men sustaining serious injuries.",
	"Retreat. Flee. Don\'t fight every battle to the death.",
	"Use the spacebar key to pause on the worldmap.",
	"Elevated terrain like hills and mountains allow you to see farther on the worldmap.",
	"Not every contract is worth the risk.",
	"Try to negotiate better payment for your contracts.",
	"Try to negotiate payment modalities that guarantee you the most money for contracts.",
	"Not every battle can be won.",
	"A life can be worth little in this world.",
	"Betraying your employer can have repercussions in the long run.",
	"Some parts of the world are more dangerous than others.",
	"Use ports to fast travel around the world.",
	"Some people will use you and throw you away.",
	"Throwing weapons can be deadly on short distances, but their accuracy drops sharply the farther away the target.",
	"Highly talented characters can come from all backgrounds.",
	"Try the Ironman mode to experience Battle Brothers the way it\'s meant to be played.",
	"Ranged weapons are less accurate at night - those of your enemies included.",
	"Make camp to have your men heal and repair their equipment faster.",
	"Use ALT + Right Click to mark items for repair in your stash. Items equipped by your men are repaired automatically.",
	"Breaking a contract will anger your employer - especially if you\'ve received advance payment.",
	"Fortifications will only offer you contracts from the noble house that owns them.",
	"Nobles give contracts only to mercenary companies with professional renown.",
	"If contract negotiations turn sour, it will damage your relations with your potential employer.",
	"You can find contract offers in the top left of settlement screens.",
	"You may find powerful named items far away from civilization by exploring or following tavern rumors.",
	"Dying is part of a mercenary\'s job description.",
	"Keep an eye on the mood of your men. If they are angry for too long, they may desert!",
	"If you keep losing to an enemy, change your tactics!",
	"The larger a party on the worldmap, the slower it moves. Yours included.",
	"Use wardogs to hunt down elusive or fleeing enemies.",
	"Use a trained falcon to discover hidden enemies in difficult terrain.",
	"Cleavers can inflict bleeding wounds.",
	"Fulfilling ambitions will raise everyone\'s mood and grant you unique rewards.",
	"Use CTRL + Left Click to attack allied parties on the worldmap. This only works if you are currently unemployed.",
	"Your men will interact with each other differently depending on their backgrounds and traits.",
	"Stunned characters get no attack of opportunity when moving inside their zone of control.",
	"Try playing a campaign in veteran mode once you\'ve gained some experience - it\'s the recommended difficulty.",
	"The minimum hit chance for any attack is 5%, and the maximum hit chance for any attack is 95%.",
	"Characters may sometimes be struck down during combat, but not outright killed, and will survive with a permanent injury.",
	"Learn from your mistakes. Don\'t just repeat them and hope you\'ll get lucky this time.",
	"The natural habitat of direwolves is the forest.",
	"You can enable faster AI turns in the options menu.",
	"Trees can be hidden in combat using the \'T\' key.",
	"Higher renown will unlock more difficult contracts and better pay.",
	"If your plan can fail with bad luck, maybe it isn\'t good enough of a plan."
];
gt.Const.LoadingScreens <- [
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_01.jpg",
	"ui/screens/loading_screen_02.jpg",
	"ui/screens/loading_screen_03.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_04.jpg",
	"ui/screens/loading_screen_07.jpg"
];
