local gt = this.getroottable();
gt.Const.CharacterTraits <- [
	[
		"trait.eagle_eyes",
		"scripts/skills/traits/eagle_eyes_trait"
	],
	[
		"trait.short_sighted",
		"scripts/skills/traits/short_sighted_trait"
	],
	[
		"trait.tough",
		"scripts/skills/traits/tough_trait"
	],
	[
		"trait.strong",
		"scripts/skills/traits/strong_trait"
	],
	[
		"trait.hesitant",
		"scripts/skills/traits/hesitant_trait"
	],
	[
		"trait.quick",
		"scripts/skills/traits/quick_trait"
	],
	[
		"trait.tiny",
		"scripts/skills/traits/tiny_trait"
	],
	[
		"trait.cocky",
		"scripts/skills/traits/cocky_trait"
	],
	[
		"trait.clumsy",
		"scripts/skills/traits/clumsy_trait"
	],
	[
		"trait.fearless",
		"scripts/skills/traits/fearless_trait"
	],
	[
		"trait.fat",
		"scripts/skills/traits/fat_trait"
	],
	[
		"trait.dumb",
		"scripts/skills/traits/dumb_trait"
	],
	[
		"trait.bright",
		"scripts/skills/traits/bright_trait"
	],
	[
		"trait.drunkard",
		"scripts/skills/traits/drunkard_trait"
	],
	[
		"trait.fainthearted",
		"scripts/skills/traits/fainthearted_trait"
	],
	[
		"trait.bleeder",
		"scripts/skills/traits/bleeder_trait"
	],
	[
		"trait.ailing",
		"scripts/skills/traits/ailing_trait"
	],
	[
		"trait.determined",
		"scripts/skills/traits/determined_trait"
	],
	[
		"trait.dastard",
		"scripts/skills/traits/dastard_trait"
	],
	[
		"trait.deathwish",
		"scripts/skills/traits/deathwish_trait"
	],
	[
		"trait.fragile",
		"scripts/skills/traits/fragile_trait"
	],
	[
		"trait.insecure",
		"scripts/skills/traits/insecure_trait"
	],
	[
		"trait.optimist",
		"scripts/skills/traits/optimist_trait"
	],
	[
		"trait.pessimist",
		"scripts/skills/traits/pessimist_trait"
	],
	[
		"trait.superstitious",
		"scripts/skills/traits/superstitious_trait"
	],
	[
		"trait.brave",
		"scripts/skills/traits/brave_trait"
	],
	[
		"trait.dexterous",
		"scripts/skills/traits/dexterous_trait"
	],
	[
		"trait.sure_footing",
		"scripts/skills/traits/sure_footing_trait"
	],
	[
		"trait.asthmatic",
		"scripts/skills/traits/asthmatic_trait"
	],
	[
		"trait.iron_lungs",
		"scripts/skills/traits/iron_lungs_trait"
	],
	[
		"trait.craven",
		"scripts/skills/traits/craven_trait"
	],
	[
		"trait.greedy",
		"scripts/skills/traits/greedy_trait"
	],
	[
		"trait.gluttonous",
		"scripts/skills/traits/gluttonous_trait"
	],
	[
		"trait.spartan",
		"scripts/skills/traits/spartan_trait"
	],
	[
		"trait.athletic",
		"scripts/skills/traits/athletic_trait"
	],
	[
		"trait.brute",
		"scripts/skills/traits/brute_trait"
	],
	[
		"trait.irrational",
		"scripts/skills/traits/irrational_trait"
	],
	[
		"trait.clubfooted",
		"scripts/skills/traits/clubfooted_trait"
	],
	[
		"trait.loyal",
		"scripts/skills/traits/loyal_trait"
	],
	[
		"trait.disloyal",
		"scripts/skills/traits/disloyal_trait"
	],
	[
		"trait.bloodthirsty",
		"scripts/skills/traits/bloodthirsty_trait"
	],
	[
		"trait.iron_jaw",
		"scripts/skills/traits/iron_jaw_trait"
	],
	[
		"trait.survivor",
		"scripts/skills/traits/survivor_trait"
	],
	[
		"trait.impatient",
		"scripts/skills/traits/impatient_trait"
	],
	[
		"trait.swift",
		"scripts/skills/traits/swift_trait"
	],
	[
		"trait.night_blind",
		"scripts/skills/traits/night_blind_trait"
	],
	[
		"trait.night_owl",
		"scripts/skills/traits/night_owl_trait"
	],
	[
		"trait.paranoid",
		"scripts/skills/traits/paranoid_trait"
	],
	[
		"trait.legend_hate_nobles",
		"scripts/skills/traits/legend_hate_nobles_trait"
	],
	[
		"trait.hate_greenskins",
		"scripts/skills/traits/hate_greenskins_trait"
	],
	[
		"trait.hate_undead",
		"scripts/skills/traits/hate_undead_trait"
	],
	[
		"trait.hate_beasts",
		"scripts/skills/traits/hate_beasts_trait"
	],
	[
		"trait.fear_beasts",
		"scripts/skills/traits/fear_beasts_trait"
	],
	[
		"trait.legend_fear_nobles",
		"scripts/skills/traits/legend_fear_nobles_trait"
	],
	[
		"trait.fear_undead",
		"scripts/skills/traits/fear_undead_trait"
	],
	[
		"trait.fear_greenskins",
		"scripts/skills/traits/fear_greenskins_trait"
	],
	[
		"trait.teamplayer",
		"scripts/skills/traits/teamplayer_trait"
	],
	[
		"trait.weasel",
		"scripts/skills/traits/weasel_trait"
	],
	[
		"trait.huge",
		"scripts/skills/traits/huge_trait"
	],
	[
		"trait.lucky",
		"scripts/skills/traits/lucky_trait"
	],
	[
		"trait.legend_steady_hands",
		"scripts/skills/traits/legend_steady_hands_trait"
	],
	[
		"trait.legend_slack",
		"scripts/skills/traits/legend_slack_trait"
	],
	[
		"trait.legend_frail",
		"scripts/skills/traits/legend_frail_trait"
	],
	[
		"trait.legend_natural",
		"scripts/skills/traits/legend_natural_trait"
	],
	[
		"trait.legend_unpredictable",
		"scripts/skills/traits/legend_unpredictable_trait"
	],
	[
		"trait.legend_predictable",
		"scripts/skills/traits/legend_predictable_trait"
	],
	[
		"trait.legend_pragmatic",
		"scripts/skills/traits/legend_pragmatic_trait"
	],
	[
		"trait.legend_light",
		"scripts/skills/traits/legend_light_trait"
	],
	[
		"trait.legend_heavy",
		"scripts/skills/traits/legend_heavy_trait"
	],
	[
		"trait.legend_firm",
		"scripts/skills/traits/legend_firm_trait"
	],
	[
		"trait.legend_ambitious",
		"scripts/skills/traits/legend_ambitious_trait"
	],
	[
		"trait.legend_aggressive",
		"scripts/skills/traits/legend_aggressive_trait"
	],
	[
		"trait.legend_gift_of_people",
		"scripts/skills/traits/legend_gift_of_people_trait"
	],
	[
		"trait.legend_double_tongued",
		"scripts/skills/traits/legend_double_tongued_trait"
	],
	[
		"trait.legend_seductive",
		"scripts/skills/traits/legend_seductive_trait"
	],
	[
		"trait.legend_fear_dark",
		"scripts/skills/traits/legend_fear_dark_trait"
	],
	[
		"trait.legend_sureshot",
		"scripts/skills/traits/legend_sureshot_trait"
	]
];

